### ISSUE TITLE
New Github repository for Sharing Cart plugin

### ISSUE THREAD

**Issue by donhinkelman** [donhinkelman/moodle-block_sharing_cart#1]
Hi Everyone, just announcing this new github location for the Sharing Cart.  Version 3.5 is now released on the Plugins Database: https://moodle.org/plugins/block_sharing_cart. For reporting issues, I hope to respond here on this repository. Sorry please re-enter any previous issues you have entered elsewhere. Thank you very much for your patience. Don

**Comment by TubsDK** [comment]
Hi Don 

Great that you have taken over for the excellent plugin. Do you happen to have a link for the old repo?

**Comment by abias** [comment]
Hi @TubsDK ,

the old repo was located on https://github.com/VERSION2-Inc/moodle-block_sharing_cart

**Comment by TubsDK** [comment]
Closed the info is display in the official moodle plugin site.
