### ISSUE TITLE
Add support for privacy API

### ISSUE THREAD

**Issue by abias** [donhinkelman/moodle-block_sharing_cart#10]
Since 2018, Moodle plugins have to support the Moodle privacy API. This API has the goal to fulfill the requirements of GDPR in Moodle. Please see details on https://docs.moodle.org/dev/Privacy_API.

It would be great if you could add Privacy API support to this plugin to make it compliant with data protection laws in EU and worldwide.

**Comment by donhinkelman** [comment]
Thank you, Alex for opening this issue, and to Sam, Johnny and Praxis developers for fulfilling this important standard of all Moodle plugins.
