### ISSUE TITLE
Improvement: Sharing cart should respect ordering of items within a section

### ISSUE THREAD

**Issue by Kathrin84** [donhinkelman/moodle-block_sharing_cart#11]
Hi Don,

while testing your plugin for the Moodle 3.6 version, I stumbled over this behavior.

**Encountered problem**
A section contains several activities and resources.
When you add the whole section to the sharing cart, the ordering of the items is not the same anymore. Then, when you restore the section to another section or course, the structure of the sharing cart will be restored. So the initial ordering is muddled up and the teacher needs to rearrange his copied section.

**Steps to reproduce**
1. Create a new course and merge this backup into the course:
[test_sharing_cart.mbz.zip](https://github.com/donhinkelman/moodle-block_sharing_cart/files/2986939/test_sharing_cart.mbz.zip)
Your course should look like this now:
![sharing_cart_course_structure](https://user-images.githubusercontent.com/4711883/54666283-a35b0f00-4ae9-11e9-8763-1dfa86b1f6fb.png)
2. Turn editing on and add the block sharing cart to this course
3. Add the whole section to the sharing cart
4. Verify that the structure within the sharing cart is different to the structure of the copied section. In my case it looks like this:
![sharing_cart_copied_section](https://user-images.githubusercontent.com/4711883/54666668-bae6c780-4aea-11e9-8d0d-09a21ef8c9b7.png)
5. Restore the whole section into another course or into another section
Verify that the structure of the restored section is the same as the one in the sharing cart.

**Propopsal**
The sharing cart should backup the items within a section in the same order.

Best, Kathrin

**Comment by donhinkelman** [comment]
Thank you Kathrin. We are now working on this issue.

**Comment by donhinkelman** [comment]
Thank you all for work on this issue. It is now closed.

**Comment by Kathrin84** [comment]
Thank you very much for this improvement! 👍

**Comment by neeesn** [comment]
We stille have this issue - we have updated sharing_cart to version 2019012000 3,6 Release 1
![billede](https://user-images.githubusercontent.com/1931926/62850537-751ddc00-bce3-11e9-88fa-3c36bc501700.png)

We are currently using moodle 3.4.3+

**Comment by bfriesenvcc** [comment]
We also still have this issue, using 2019012000, 3.6, release 1.

**Comment by donhinkelman** [comment]
Thank you for reporting and confirming that this issue still remains. I don't know when the programmers can work on this, but I hope it will be fixed in the next release.
