### ISSUE TITLE
Error after upgrading to version 2021072300 (3.10, release 6) in moodle 3.11.1+ (Build: 20210716)

### ISSUE THREAD

**Issue by canatojr** [donhinkelman/moodle-block_sharing_cart#110]
Hello!

After updating the Sharing Cart to its latest version, the message below is displayed when trying to enter any course with the Sharing Cart Block enabled.

Sincerely,
Osvaldo

//---------------------------//
  
Erro
Exceção - syntax error, unexpected 'moodle_database' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)
Debug info:
Error code: generalexceptionmessage
Stack trace:
line 39 of /blocks/sharing_cart/classes/repositories/course_repository.php: ParseError thrown
line ? of unknownfile: call to core_component::classloader()
line 77 of /blocks/sharing_cart/classes/controller.php: call to spl_autoload_call()
line 84 of /blocks/sharing_cart/block_sharing_cart.php: call to block_sharing_cart\controller->render_tree()
line 341 of /blocks/moodleblock.class.php: call to block_sharing_cart->get_content()
line 235 of /blocks/moodleblock.class.php: call to block_base->formatted_contents()
line 1181 of /lib/blocklib.php: call to block_base->get_content_for_output()
line 1239 of /lib/blocklib.php: call to block_manager->create_block_contents()
line 374 of /lib/blocklib.php: call to block_manager->ensure_content_created()
line 3980 of /lib/outputrenderers.php: call to block_manager->region_has_content()
line 40 of /theme/boost/layout/columns2.php: call to core_renderer->blocks()
line 1396 of /lib/outputrenderers.php: call to include()
line 1326 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 245 of /course/view.php: call to core_renderer->header()

**Comment by mukuuh** [comment]
After Upgrading I got the Error-Messages:
![grafik](https://user-images.githubusercontent.com/14321456/126891220-66883b0e-8ca3-412e-ad48-f06e3346ff71.png)
After I removed it and took a older Version it works.

**Comment by mattgig** [comment]
I came across the same problem: It only occurs when you try to edit a course which contains the sharing cart plugin.
Moodle: 3.11.1
PHP: 7.3
After reverting back to an older version, the problem disappeared.

**Comment by donhinkelman** [comment]
Thank you for your reports, I have reproduced the error and we are working on it now. And ask you to download 3.10, release 3 while we fix the problem in release 6.
