### ISSUE TITLE
v3.10 release 3 (2021062600) marked as compatible with moodle 3.9 but branch MOODLE_39_STABLE not updated

### ISSUE THREAD

**Issue by uvigo-atic** [donhinkelman/moodle-block_sharing_cart#114]
At the moodle plugins directory site, `v3.10 release3` is marked as compatible with moodle 3.9, 3.10, 3.11...:

https://moodle.org/plugins/block_sharing_cart/versions

But the branch origin/MOODLE_39_STABLE is not updated (it appears as a stale branch, updated 4 months ago):

https://github.com/donhinkelman/moodle-block_sharing_cart/branches/stale

If the code in MOODLE_310_STABLE is indeed compatible with moodle 3.9, could the branch MOODLE_39_STABLE be updated to reflect the possibility for moodle 3.9 sites to update to the new version?.

Thanks in advance

**Comment by frederikmillingpytlick** [comment]
Hi @uvigo-atic,

The moodle 3.9 branch should now be up to date and have the new features/bug fixes :)
