### ISSUE TITLE
Bug: Activities or resources without a backup and restore implementation cause error in sharing cart

### ISSUE THREAD

**Issue by Kathrin84** [donhinkelman/moodle-block_sharing_cart#12]
Hi Don,

while testing your plugin for the latest Moodle 3.6 version we stumbled over this problem.

**Problem**
By trying to move an activity or resource to the sharing cart which does not has implemented the backup and restore mechanism, sharing cart errors.
The error message looks like this:
![operation_error](https://user-images.githubusercontent.com/4711883/54684607-0ada8400-4b15-11e9-9586-93f2162bf733.png)
This is just an excerpt. The content of the error message is a whole HTML file that says ```Exception - Class 'backup_[activityname]_activity_task' not found```

**Steps to reproduce**
1. Install a plugin that does not contain the backup and restore functionality. Currently, we could trigger this with mod_groupmembers (https://moodle.org/plugins/mod_groupmembers)
2. Go to a course and add the resource "groupmembers" to your course
3. Add this to the sharing cart
4. Verify that you see the error message
5. Verify that the resource is not added to the sharing cart

**Proposal**
* Check if the selected item has implemented the backup and restore functionality. If not, then skip this item and maybe inform the user that this item cannot be added to the sharing cart.
* Make the error message human readable.

Thanks and best, Kathrin

**Comment by donhinkelman** [comment]
Hi Kathrin, thanks for explaining this problem and making a clear proposal. Very human readable! And important to implement as there are several non-backup/restore plugins out there. I am sorry we are so slow to respond but our programmer is so busy doing his studies.
