### ISSUE TITLE
Feature request: Bulk copy content into section

### ISSUE THREAD

**Issue by lassnj** [donhinkelman/moodle-block_sharing_cart#120]
Thank you for the great plugin. We got a feature request from our users:
Similar to the bulk delete it would be nice if you could select several resources in the sharing cart at once and bulk insert them into a section of the new course.

**Comment by donhinkelman** [comment]
Hi Lassnj, thanks for the request. Are you aware that the Sharing Cart has a section copy feature? Look for the basket icon near the section title. Once you copy a section and then paste into another course, you can delete unwanted items.

**Comment by lassnj** [comment]
Hi Don,
thanks for the reply. I am aware of the section copy feature, the problem is, that resources are not always grouped in a section in the original course, so some users have a lot of single resources in the cart that they have to select one by one to insert into a section. It would be nice to check a checkbox in the cart and select all the resources that should be inserted at the end of a section in the target course. If the section is very long there is a lot of scrolling involved when you have to do it one by one. So this feature would be great.
Regards
Julia

**Comment by donhinkelman** [comment]
Hi Julia, I think I understand what you are asking for. I personally have not tried to do what you describe. So I would like other users to describe their workflow and how the Sharing Cart can aid their materials/activity creation process. Also I want to know how the Sharing Cart can work together with MoodleNet. Do you have any suggestions there?  I imagine that the Sharing Cart could interconnect with a MoodleNet server, or federated Moodle Net server to search and share activities and resources. This is a long term design process, but I appreciate your suggestion. If you are coming to Barcelona in September 2022, you may want to discuss with me or Tue, who is the head of Praxis and a maintainer of the Sharing Cart.

**Comment by lassnj** [comment]
Hi Anders and Don,
thanks for your replies and suggestions and sorry for my late response. We tested the drag&drop feature on our moodle 3.11 but it didn't work properly, so we will test it again when we upgrade to 4.x. 
We are thinking about going to Barcelona in 2023, but still need the ok of our superiors.
Thanks for your great work!

Kind regards
Julia

**Comment by frederikmillingpytlick** [comment]
The sharing cart have been completely reworked since this issue was reported, I will be closing the issue.

Feel free to let us know if you'd still like to suggest a feature :)
