### ISSUE TITLE
Basket icon not appearing when using non-standard course format setting

### ISSUE THREAD

**Issue by martinmeadows** [donhinkelman/moodle-block_sharing_cart#121]
There seems to be an issue with the course format "flexible sections". In a course where I had enabled the Sharing Cart block, the basket icon only appeared beside sections, not activities. When I changed that to the standard "Topics" format, or to another non-standard format called "Tiles",  the basket icon then appeared beside individual activities/resources as well.

Moodle version 3.11.6+ (Build: 20220405)
Flexible section course format version 3.5.1  (2020051100)

**Comment by donhinkelman** [comment]
Thank you Martin, for testing the Sharing Cart on Flexible Sections course format. This kind of issue happens with non-standard course formats and as a general rule we ask the course format maintainers to fix it or make a pull request. Praxis tests the Sharing Cart in standard themes such as Boost. However, as Praxis works on other issues, they may keep this in mind and  fix it along the way. I really would like the Sharing Cart to work smoothly with every major Moodle theme.
