### ISSUE TITLE
Sharin cart icon hidden

### ISSUE THREAD

**Issue by alina-kiz** [donhinkelman/moodle-block_sharing_cart#134]
Hello,
we have a moodle version 3.9.17+ (Build: 20220922).
After update block sharing cart to version 4.0, release 1 (2022092301) Icon sharing cart nearby activity was hidden.

**Comment by donhinkelman** [comment]
My apologies for not explaining. The new version 4.0 does direct drag and drop into the Sharing Cart block. If you prefer clicking the Sharing Cart icon, please go to Sharing Cart settings to return to the original process. This new way will work better with a variety of course formats and themes, however it will take getting used to.

**Comment by donhinkelman** [comment]
Frederik, could we make a explanation or popup appear to help people not used to this new approach? Or make the click icon a default for the next three months.

**Comment by alina-kiz** [comment]
Thank you for explaining. It works with settings and return to the original process.
I have try drag and drop into the Sharing Cart block, but it does not work on my moodle.
Maybe I make something wrong

**Comment by donhinkelman** [comment]
I wonder why the drag and drop does not work in your Moodle. Could you answer these questions?  What is your browser? What is your Moodle theme? What is your Moodle course format? Was the Sharing Cart block installed in your Moodle? Did you see any error messages?

**Comment by frederikmillingpytlick** [comment]
Hi @donhinkelman and @alina-kiz

Praxis will take a look at it :)

**Comment by donhinkelman** [comment]
Frederik and Anders, I received some direct comments from major users that the Sharing Cart needs to be accessible by default. Double check that persons (teachers) with disabilities can drag and drop on a touch tablet with ease. I understand that you have made the Sharing Cart basket icon clickable by default, is that correct, in Sharing Cart 4.0, release 2?

**Comment by donhinkelman** [comment]
Now the README file says: "Sharing cart basket icon now hidden Drag item directly into your cart. Or change settings to prefer old way of clicking basket."
May I rewrite that to **"Sharing Cart basket icon can be optionally hidden. The drag-and-drop feature directly into Sharing Cart block is now optional in the settings. Admins should check the accessibility needs of teachers before changing to drag-and-drop default."**

**Comment by frederikmillingpytlick** [comment]
> Double check that persons (teachers) with disabilities can drag and drop on a touch tablet with ease. 

We've not tested this with a physical device. but I've just tried using chrome devtools to simulate a tablet and the new drag-drop functionality didn't seem to work.

> Now the README file says: "Sharing cart basket icon now hidden Drag item directly into your cart. Or change settings to prefer old way of clicking basket."
May I rewrite that to "Sharing Cart basket icon can be optionally hidden. The drag-and-drop feature directly into Sharing Cart block is now optional in the settings. Admins should check the accessibility needs of teachers before changing to drag-and-drop default."

You're free to rewrite it if you feel it is inadequate or badly worded :)

**Changes in Sharing Cart 4.0, release 2:**
1. The old way of clicking the basket icon is now default. - Users who have already upgraded to `4.0, release 1` will need to manually change it back to the old way in settings.
2. UI/UX improvements

**Comment by donhinkelman** [comment]
Thank you, Frederik!  I understand now and I will try to make all notes and README consistent. I am also troubleshooting some users on SNS, and I will advise them properly now. Thanks, and your English is perfect. Just me who is confused because I am not able to test the Sharing Cart 4.0, release 2, on my own site.
