### ISSUE TITLE
Remove a sharing cart item if the corresponding backup file was removed from the "User private backup area"

### ISSUE THREAD

**Issue by abias** [donhinkelman/moodle-block_sharing_cart#14]
Items which are added to the Sharing Cart are visible in the "User private backup area" and could be deleted there by the user by mistake (#2 handles this) or by purpose.

Now, when a backup file was removed from the "User private backup area", the corresponding item is still there in the Sharing Cart.
And when the user tries to restore this item, he only gets an ugly error message saying
`Fehler: Call to a member function copy_content_to() on boolean`

I would like to propose to remove a sharing cart item if the corresponding backup file was removed from the "User private backup area". This isn't a really nice solution, but it's the only logical thing which should be done instead of keeping a broken item in the Sharing Cart.

**Comment by johnnypraxis** [comment]
This bug is fixed.

The error message won't be displayed anymore. The item is removed from the Sharing Cart if the file is removed from the "User private backup area".

**Comment by donhinkelman** [comment]
Thank you very Johnny. As Alex said, this isn't a nice solution, but much better than ugly error messages that a user has no idea about.

**Comment by donhinkelman** [comment]
Actually, I think you made a rather elegant solution--I just read in release 14 you added a prefix to each file to indicate that it is a Sharing Cart file.
