### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by ozyurt45** [donhinkelman/moodle-block_sharing_cart#144]
Hi, I have successfully copied a quiz item to basket. But I get error when I try to paste it back.

Error message is 

"Exception - Too few arguments to function restore_dbops::restore_get_question_categories(), 2 passed in [dirroot]/blocks/sharing_cart/backup/moodle2/restore_fix_missing_questions.php on line 52 and exactly 3 expected"

**Comment by donhinkelman** [comment]
Thank you for reporting your problem. How can we replicate this error?  Could you tell us more about your system? - Moodle version, theme version, Sharing Cart version? Does this happen in all browsers?  Does it happen with other quizzes on your site?

**Comment by donhinkelman** [comment]
Thank you, ematilla, for reporting the same issue. I will assign this to our Praxis colleagues.

**Comment by frederikmillingpytlick** [comment]
As @donhinkelman also mentioned, this seems to be the same issue as #118 and I am therefore closing this issue. Further comments can be made there.

I've created a task on our task board for someone at Praxis to take a look at it in the near future
