### ISSUE TITLE
Compatibility with Boost Union Theme

### ISSUE THREAD

**Issue by donhinkelman** [donhinkelman/moodle-block_sharing_cart#145]
There is a strong recommendation among the Moodle User Association, and especially the German-speaking community of universities to use the "Boost Union" theme: https://moodle.org/plugins/theme_boost_union

I am not able to test this, so I like to ask for a volunteer to test the Sharing Cart with this theme.

**Comment by AraPraxis** [comment]
Hello @donhinkelman

I've tested Boost Union on Moodle 4.0 & 4.1 and it seems to work as intended.
So if the users wants to use the sharing cart plugin and Boost Union theme, then that's possible.

Kind regards,
Anders Rasmussen

Praxis Team

**Comment by donhinkelman** [comment]
Thank you, Anders. I also received a report from Alex Bias that Sharing Cart and Boost Union are working well together in 4.1. I will close this issue.
