### ISSUE TITLE
Improvement: Add information dialogue to the restore process

### ISSUE THREAD

**Issue by Kathrin84** [donhinkelman/moodle-block_sharing_cart#15]
Hi Don,

we've got yet another proposal for your plugin:

Currently, while adding items to the sharing cart, the user gets a hint from the UI by showing a spinner that the plugin is doing something.
Unfortunately, while restoring items from the sharing cart to the course there's no visual hint. In both cases (restoring a single item or a whole section), the user only sees some action in the url bar but no further information within Moodle.

So I would like to propose to add the same progress bar as proposed in  https://github.com/donhinkelman/moodle-block_sharing_cart/issues/13 for the restoring process. With this the user will be more aware what the plugin is processing at a certain point in the process.

Best, Kathrin

**Comment by Mikkeljeppesen1** [comment]
@donhinkelman in my newest pull request I made a spinner when you restore with sharing cart

**Comment by Mikkeljeppesen1** [comment]
@donhinkelman - can you close this one?
