### ISSUE TITLE
Option for use of Sharing Cart Icons or previous method of embedded in Activity options

### ISSUE THREAD

**Issue by bradnielsen2981** [donhinkelman/moodle-block_sharing_cart#153]
This is just a suggestion for improvement. It would be great if there could be a configuration option where you could choose Drag or Drop, use of Basket **OR** simply addition to the  **. . .** menu.

I quite liked the old method.

**Comment by AraPraxis** [comment]
Hello @bradnielsen2981

Since we haven't heard from you, we see the issue as closed.

If you have any further problems or questions, then feel free to open the issue again or create a new one.

Kind regards,
Anders Rasmussen

Praxis Team

**Comment by donhinkelman** [comment]
Yes, this is closed. And thank you Anders and Praxis for making Drag-and-drop or Basket as a setting.
