### ISSUE TITLE
Feature request: Sharing to public

### ISSUE THREAD

**Issue by fishfree** [donhinkelman/moodle-block_sharing_cart#154]
The purpose is to facilitate learning resources sharing and reuse. Now, sharing_cart is limited to share own resources between own courses.
Or, teachers can share own resources to some courses, which can be configured by admin. In these resource-sharing-specialized courses, even a non-teacher user can copy the shared resources to his own courses.

**Comment by donhinkelman** [comment]
Hi fishfree, I think you put your your finger on the most important new feature of the Sharing Cart--sharing to the public. Now in my school. any teacher can share to any course. It is an open sharing culture. Is your school more restrictive? Why don't you ask your Moodle admin to allow more sharing? To the public? Wow, great idea. Is that the same as sharing to Moodle.net?

**Comment by fishfree** [comment]
@donhinkelman Sounds great! How do you make it in your school? Could you share with me please?

**Comment by AraPraxis** [comment]
Hello @fishfree @donhinkelman 

Is there a specific way you see this being done?

At the moment a teacher could just upload the specific resources to a course, if they wish to share their resources - And if a lot of teachers choose to show a resource which is just "given"/shown to the student anywhere, then the list could become very long very fast.

Is it a setting a teacher should set on each course, e.g:
"Make your sharing cart public in course: Yes/No" - Then a student can see a list of the teacher's resources, on the specific course..? This would change from course to course, depending on the teacher.

Kind regards,
Anders Rasmussen

Praxis Team

**Comment by AraPraxis** [comment]
Hello @fishfree 

I've discussed this further with my superior and we see it as either "dangerous" (for performance) if the users get a lot of activities from different teachers that thinks that the activity/section would be nice to have easy accessible.
Hereto if we narrow it down to show for a single course or category, the users could just easily see the activities in the course anyway.

We've chosen to close the issue.

Kind regards,
Anders Rasmussen

Praxis Team

**Comment by donhinkelman** [comment]
Yes, I agree to close this issue for two reasons: 1) the sharing cart is intended for teachers to share their learning activities between their own courses, and between teachers in the same institution. And 2) because MoodleNet will allow sharing of content publicly. MoodleNet 3.0 is due out soon, and Moodle 4.2 is due out soon. We should see the system of bi-directional sharing that HQ has announced will come in these versions or near future versions.
