### ISSUE TITLE
CR missing in Moodle 4.0.6+

### ISSUE THREAD

**Issue by johnw337** [donhinkelman/moodle-block_sharing_cart#156]
I installed the actual plugin 4.0 R4 on Moodle 4.0.6+ and there ist a problem: 
There is missing a carriage return while displaying the single lines. 
So I have to scroll the block to the right to find the single entrys.
Before the Update to Plugin 4.0 the displaying vertically in lines in one column was o.k.
I tested the same plugin on Moodle 4.1.1+ (actual Version). Here it works fine.
I deleted the "old" Block in the curse in Moodle 4.0.6+, re-installed the plugin 4.0 R4 and activated the Sharing cart Block again - no effect, all items in one line.

**Comment by donhinkelman** [comment]
Frederik, could you look at this issue?  Thank you.

**Comment by sanjan1809** [comment]
Hello!
Same happened when upgrading from Moodle3.11.11 to 3.11.12 without updating the plugin.
Probably something changed in moodle core?
![grafik](https://user-images.githubusercontent.com/79969581/220416745-0cf462cf-edf4-4b2f-bdad-65fc6290f03a.png)

**Comment by donhinkelman** [comment]
I don't know, you may be right, Sanjan. By the way, I just noticed this post in the General Help of moodle.org forums. I wonder if it is a similar or identical problem.  https://moodle.org/mod/forum/discuss.php?d=443299#p1786098

**Comment by johnw337** [comment]
Hello,
I read the post at the forum (see Link above).
And yes - it's the same problem...
I am working with Moodle 4.0.6+ and theme "boost".
I copied the shown code to 
admin/../boost-settings/extended settings/Raw initial SCSS:

.block_sharing_cart ul.tree.list {display: contents;}
.block_sharing_cart ul.tree.list > li {display: inherit;}
.block_sharing_cart ul.tree.list > li .toggle-wrapper {width: auto;}
.block_sharing_cart ul.tree.list > li span.commands {margin-left: 5px;}
.block_sharing_cart ul.tree.list > li ul.list {display: block;}
.block_sharing_cart ul.tree.list > li ul.list > li {display: block;}
.block_sharing_cart ul.tree.list > li ul.list .instancename {width: auto;}
.block_sharing_cart ul.tree li > div .instancename {width: auto;}
.block_sharing_cart ul.tree.list > li ul.list::before,
.block_sharing_cart ul.tree.list > li ul.list li::before {content: none; outline: none;}

and now it works fine.

Maybe this info helps solving the problem.
Best regards

**Comment by michalwz** [comment]
Hey,
We are on moodle 4.1.1 and having the same problem.
Will it be fixed?
Thanks

**Comment by donhinkelman** [comment]
Sorry, everyone about this bug #156. 2-3 weeks ago it was reported and I assigned Praxis to work on it. Today, I went to the Praxis support desk and asked it be fixed urgently. They replied, "Your request has been assigned case number (42688) and you can follow the case online here and you will receive updates by email. We are looking into the case and will get back to you as soon as possible." I think this will hurry things up.

**Comment by mcardle** [comment]
Hi all, 

We will have a look at this and try to come with a solution as soon as possible.

// Ulrik McArdle, Praxis

**Comment by sampraxis** [comment]
Is there anyone who want to test the fix?
We just want to make sure it works for the people who got the issue.
https://github.com/praxisdigital/moodle-block_sharing_cart/commit/b7544c5519b48da1622eb3a9e42080d4bd0bdff0

**Comment by donhinkelman** [comment]
Thank you Sam for following up on this so quickly. With no further comments, I will close the issue.
