### ISSUE TITLE
Process of adding to sharing cart / adding from sharing cart to section is slow

### ISSUE THREAD

**Issue by Kathrin84** [donhinkelman/moodle-block_sharing_cart#16]
Hi Don,

as I've tested your plugin for Moodle 3.6 again, I realized again that the processes of adding either to sharing or to the course needs a lot of time. I wanted to add a section with different activities (about approximately 20) to the sharing cart and after more than 5 minutes the process was not finished yet...

We think that's because each item is processed sequentially as a own backup and one backup will only start after the previous backup was finished.

Maybe there's a possibility to start another backup without the need for the first backup to finish? We think this would increase the speed of the process.

Edit - just some more thoughts:
Maybe this feature could help when it's finished and integrated into core: https://tracker.moodle.org/browse/MDL-28505
OR 
Maybe thinking about making them as a asynchronous adhoc tasks. But then the ad hoc tasks need to be tracked to be able to give the user feedback when the whole process is finished...

Best, Kathrin

**Comment by donhinkelman** [comment]
Moving from single activity copy to full section copy has made this issue prominent. I will have to consider how we should approach the speed of complicted section copies.

**Comment by JoseFSala** [comment]
After installing «Collapsed Topics format_topcoll | 3.6.1.0 2018121903» I cannot copy sections. I am using «Moodle 3.6.7+ (Build: 20191122)». Any suggestion?

Thanks in advance,
José



»

**Comment by JoseFSala** [comment]
I've just realized that there is a duplicated "Copy to Sharing Cart" entry in the edit menu of the first item under the topic title. The bottom "Copy to Sharing Cart" entry has copied the section to the sharing cart.

**Comment by Mikkeljeppesen1** [comment]
@Kathrin84 
please try updating your plugin - lots of things have happened. If you experience long copy time after updating please let me know what's inside of the section you try to copy. If you have a quiz with a lot of question from the question bank, that could cause the problem too.

I will see if I can improve the copy/backup method.

**Comment by Mikkeljeppesen1** [comment]
@JoseFSala 

The problem you have, is it the same as this issue?
https://github.com/donhinkelman/moodle-block_sharing_cart/issues/32

If not, please create an issue separately. Then its easier to keep track of the issues with sharing cart

**Comment by jprovasnik** [comment]
I'm on Moodle 3.7 and though Sharing cart has been fine for the majority of the year, this past month, it's been taking some users 10 minutes to add a simple Label or Page resource into the sharing cart. The page would then crash. Then, after cache clearing and maybe 10 minutes later, when we can log back into Moodle, the label or page resource either: 
1 - never made it into the cart
2 - ends up being in the cart several times

This is happening on and off with teachers, generally in longer courses. 
I'm not sure where to being troubleshooting so am looking for advise as it seems to relate to this thread.

**Comment by jprovasnik** [comment]
My issue was resolved by unchecking "Badges" from the automated backup defaults. Even though I have automated backups turned off on my site, I believe sharing cart uses settings from there?

**Comment by frederikmillingpytlick** [comment]
Hi all, does this issue still persist?

**Comment by JoseFSala** [comment]
I don't know since I am not using Moodle this school year. My school is using Google Classroom.

**Comment by abias** [comment]
I am a colleague of the issue creator @Kathrin84 and am answering on this issue on behalf of her as she is currently not working in the Moodle area anymore.

I can say that, in recent versions of sharing cart, we haven't seen massive item adding times anymore. Sure, sharing cart is not rocket-fast, but this is a problem of the underlying backup and restore features of Moodle core and not necessarily of sharing cart itself.

Thus, from my point of view, the issue could be closed for now.

**Comment by frederikmillingpytlick** [comment]
Thank you for your response @abias, i will be closing the issue then.
