### ISSUE TITLE
Copying H5P activity shows error

### ISSUE THREAD

**Issue by azmatksa** [donhinkelman/moodle-block_sharing_cart#160]
Hi, 

When we're using without H5P activity it works while if we've a H5P activity then during copy the section on Sharing cart it shows the below error messa.ge

![image](https://user-images.githubusercontent.com/49816686/224926740-c673dd39-a7e3-4626-aced-933b7f5fd9be.png)

**Comment by donhinkelman** [comment]
Hello azmatksa, thank you for reporting the issue. I do not have an H5P to test with. Could you install and confirm that the latest release  4.0 v5 gives the same problem?

**Comment by AraPraxis** [comment]
Hello @azmatksa 

Since we haven't heard from you, we see the issue as closed.

If you have any further problems or questions, then feel free to open the issue again or create a new one.

Kind regards,
Anders Rasmussen

Praxis Team

**Comment by azmatksa** [comment]
Hi @AraPraxis, 
Its okay to close, I noticed the issue occurring only when use third party interactive content (hvp) plugin while the core Moodle H5P working fine.

cc: @donhinkelman
