### ISSUE TITLE
Problems with version 202212200

### ISSUE THREAD

**Issue by kueppersf** [donhinkelman/moodle-block_sharing_cart#162]
Hello!
We are having issues with sorting activities in the Sharin Cart on moodle versions 3.11.13 and 4.1.0. Here the copied activities are shown next to each other (activity 1, activity 2). In Moodle version 4.1.2 they are stored one below the other as before. This leads to a problem with the selection of activities in the target course.

Best regards
Friedhelm

**Comment by AraPraxis** [comment]
Hello @kueppersf

Could it be possible that it's the same error as in this issue? https://github.com/donhinkelman/moodle-block_sharing_cart/issues/161

If so then try to update to Release 5 and see if it works! :)

If not I'd like to see a picture of the error, and any information you could give to why the error might appear, moodle version in the picture, etc.
Please note that we do not intent to update the Sharing cart prior to Moodle 4.0 - However we do follow the Moodle releases and are willing to fix any security risks regarding this plugin.
https://moodledev.io/general/releases

Kind regards,
Anders Rasmussen

Praxis Team

**Comment by AraPraxis** [comment]
Hello @kueppersf 

Since we haven't heard from you, we see the issue as closed.

If you have any further problems or questions, then feel free to open the issue again or create a new one.

Kind regards,
Anders Rasmussen

Praxis Team

**Comment by kueppersf** [comment]
Hello!

 

The problem is not solved yet! However, I understood that there would be no more adjustments for Moodle 3.11.x. That's why I tried to install an older sharing_cart version in Moodle, which worked, but doesn't solve the problem either. It works in Moodle 4. In July we want to upgrade our 200 Moodle instances to 4.1 or 4.2. After that the problem would be solved. But if they have a short-term solution, that would be great.

 



 

Kind regards,

 

Friedhelm Küppers

 

Moodle-Beratung im Auftrag des

Niedersächsischen Landesinstitut für

schulische Qualitätsentwicklung

 

 

Von: Anders Rasmussen ***@***.***> 
Gesendet: Dienstag, 18. April 2023 12:32
An: donhinkelman/moodle-block_sharing_cart ***@***.***>
Cc: kueppersf ***@***.***>; Mention ***@***.***>
Betreff: Re: [donhinkelman/moodle-block_sharing_cart] Problems with version 202212200 (Issue #162)

 

Hello @kueppersf <https://github.com/kueppersf> 

Since we haven't heard from you, we see the issue as closed.

If you have any further problems or questions, then feel free to open the issue again or create a new one.

Kind regards,
Anders Rasmussen

Praxis Team

**Comment by donhinkelman** [comment]
Hello, Friedhelm. Thank you for reporting that the issue is not solved for 3.11. If Anders has time, I will ask him to work on backporting the fix to 3.11.  I presume it is the same problem reported in #161.

**Comment by AraPraxis** [comment]
Hello @kueppersf, @donhinkelman 

I'll put it on our board to backport the 4.0 fixes to 3.11, but we won't put it as a high priority, as it's not a security risk and we intent to follow the Moodle releases.
https://moodledev.io/general/releases

Kind regards,
Anders Rasmussen

Praxis Team

**Comment by kueppersf** [comment]
Thanks!

 

Von: Anders Rasmussen ***@***.***> 
Gesendet: Mittwoch, 19. April 2023 11:01
An: donhinkelman/moodle-block_sharing_cart ***@***.***>
Cc: kueppersf ***@***.***>; Mention ***@***.***>
Betreff: Re: [donhinkelman/moodle-block_sharing_cart] Problems with version 202212200 (Issue #162)

 

Hello @kueppersf <https://github.com/kueppersf> , @donhinkelman <https://github.com/donhinkelman> 

I'll put it on our board to backport the 4.0 fixes to 3.11, but we won't put it as a high priority, as it's not a security risk and we intent to follow the Moodle releases.
https://moodledev.io/general/releases

Kind regards,
Anders Rasmussen

Praxis Team

**Comment by frederikmillingpytlick** [comment]
Hi @kueppersf, sorry we didn't get the time to look at your issue again before now.

Moodle 3.11 have been out of support for some time now, so closing the issue.
