### ISSUE TITLE
content run out of the screen on moodle 4.1+

### ISSUE THREAD

**Issue by michalwz** [donhinkelman/moodle-block_sharing_cart#165]
Hey,
On moodle 4.1+ (we are currently on 4.12) with version sharing cart 2023032300
we are also having the problem of conntent running out of the screen.
in RTL lang it is running out to the left.
![image](https://user-images.githubusercontent.com/46929849/234176836-191ec1a1-7062-4559-82a9-cb95eb06f776.png)
![image](https://user-images.githubusercontent.com/46929849/234176852-d36355ab-dc7e-4412-b7e2-ab98ee908aed.png)

related to #161

**Comment by michalwz** [comment]
Hey,
Any plans of fixing it?
Thanks

**Comment by tsbartel** [comment]
We experience the same Issue on Moodle 4.1.x under either theme_boost or a child theme theme_boost_union.

Easy fix by adding the following to the beginning of `custom.css`:
```
/* SHARING CART TREE START */

.block_sharing_cart div.card-text ul.tree {
    display: flex;
    flex-wrap: wrap;
}
```

**Comment by AraPraxis** [comment]
Hello @michalwz

Since we haven't heard further and other contributers have had the same issue and added a fix, we see the issue as closed.

If you have any further problems or questions, then feel free to open the issue again or create a new one.

Kind regards,
Anders Rasmussen

Moxis Team
