### ISSUE TITLE
Re-implement REST API to use Moodle web services

### ISSUE THREAD

**Issue by golenkovm** [donhinkelman/moodle-block_sharing_cart#166]
Hi team,

I would like to flag some concerns regarding the current REST API implementation.

Sesskey/user/permission checks seem flakey https://github.com/donhinkelman/moodle-block_sharing_cart/blob/63bc1242cc6034749d0529ce20866c2f66daef14/classes/controller.php#L697
  - Appears like inside some of the functions themselves it checks sesskey + checks if the record is the same as the $USER
  - No checks for "is_userdata_copyable_section" action
  - No Checks for 'is_userdata_copyable" action
  - No checks for "render_tree" action
  - No checks for the "backup_section" action (doesn't validate sesskey)
  - No checks for the "delete_directory" action - doesn't validate sesskey nor User - it does get the $USER context but if it doesn't validate sesskey, it might be possible to spoof the $USER
  - No checks for "ensure_backup_in_module" action
  - REST api seems to be used by the JS used in the block. Really should be a Moodle webservice

Cheers,
Misha

**Comment by donhinkelman** [comment]
Thank you, Misha, for reporting this. Assigning to Frederik.

**Comment by frederikmillingpytlick** [comment]
The sharing cart have been completely reworked since this issue was reported and we've now no longer got any janky services, I will be closing the issue.

Thanks for suggesting this :)
