### ISSUE TITLE
Exposed stacktraces

### ISSUE THREAD

**Issue by golenkovm** [donhinkelman/moodle-block_sharing_cart#167]
The plugin seems to expose stacktraces if it throws an exception https://github.com/donhinkelman/moodle-block_sharing_cart/blob/63bc1242cc6034749d0529ce20866c2f66daef14/rest.php#L107-L121

**Comment by frederikmillingpytlick** [comment]
It is default Moodle behaviour to print exceptions and stacktraces when debugging is enabled.

Closing issue

**Comment by golenkovm** [comment]
I'm actually confused (by myself). Can't remember what was the actual issue with this. There probably was something. I should provide more details when I was raising the issue (screenshots, use cases etc). Happy with the issue being closed until it shows back on my (or someone's else) radar and I/we have more details on this.

Cheers,
Misha
