### ISSUE TITLE
Custom URL parameters are removed when inserting items

### ISSUE THREAD

**Issue by Snowdle** [donhinkelman/moodle-block_sharing_cart#168]
When restoring an item from  the sharing cart to a course, any custom URL parameters are removed when the page reloads

**Comment by donhinkelman** [comment]
Again, thank you, Snowdle. I will assign this to Frederik and please reassign if that is not appropriate.

**Comment by AraPraxis** [comment]
Hello @donhinkelman

@Snowdle is a new part of our team, and I've personally looked through his code on our branch, and it should be ready for you to test, as we've done aswell.

I'll also note that we've "branched" out from Praxis and our team, who works/focuses on Moodle plugins is now called Moxis, but we're still related and working with Praxis :)

Kind regards,
Anders

**Comment by frederikmillingpytlick** [comment]
This issue should now be fixed.

Fixed versions:
* 4.1, release 2 2023.07.05
* 4.0, release 7 2023.07.05
