### ISSUE TITLE
Sharing cart does note restore folders recursively

### ISSUE THREAD

**Issue by Snowdle** [donhinkelman/moodle-block_sharing_cart#169]
When inserting a folder, with other folders inside, nothing happens. The items are only inserted, if they at inside the first folder. This might be an edge case, but the folders should probably be restored recursively to get all items in all subfolders

**Comment by donhinkelman** [comment]
Thank you, Snowdle, for reporting this issue. I have not tested your case, but I will assign this to our Praxis colleagues.

**Comment by AraPraxis** [comment]
Hello @donhinkelman

@Snowdle is a new part of our team, and I've personally looked through his code on our branch, and it should be ready for you to test, as we've done aswell.

I'll also note that we've "branched" out from Praxis and our team, who works/focuses on Moodle plugins is now called Moxis, but we're still related and working with Praxis :)

Kind regards,
Anders
