### ISSUE TITLE
Fix / Improve dropzone

### ISSUE THREAD

**Issue by Kathrin84** [donhinkelman/moodle-block_sharing_cart#17]
Hi Don!

We've already talked about this some time ago via email and this issue.

Currently, the dropzone arrow is added as a CSS content, but this may cause problems with adding the icon:
![dropzone_icon_bug](https://user-images.githubusercontent.com/4711883/54810073-69bf0b00-4c85-11e9-9023-f352355e5823.png)
Furthermore, the way it is currently implemented is no straight forward and could be improved in any case.

I'll create a pull request for this issue. We would be happy if you would decide to integrate it into your plugin!

Best, Kathrin

**Comment by donhinkelman** [comment]
Thank you Kathrin, this issue has been merged and now closed.
