### ISSUE TITLE
Moodle 4.3 compatible version

### ISSUE THREAD

**Issue by michael-milette** [donhinkelman/moodle-block_sharing_cart#177]
Hi @donhinkelman , 

Do you have any thoughts on when a Moodle 4.3 compatible version might become available?

Best regards,

Michael Milette

**Comment by donhinkelman** [comment]
Thanks, Michael, for asking. Anders of Praxis has made two major commits to update Sharing Cart to handle the changes in 4.3. If I merge his pull requests, would you be willing to test the new SC 4.3 in the coming week?  It would really help as I do not have a 4.3 server ready.

**Comment by donhinkelman** [comment]
Hi Michael, I have merged the pull requests which should make Sharing Cart compatible with Moodle 4.3. Could you download this latest version from github, test it, and report your experience?  Thanks!

**Comment by donhinkelman** [comment]
To Michael and others who have downloaded the latest Sharing Cart 4.3: Let me know how it works for you, and if reports are good, I will post the plugin in the Moodle Plugins Database.

**Comment by michael-milette** [comment]
Hi @donhinkelman ,

I was hoping to get around to testing this weekend but it didn't happen. I will be testing, hopefully this week as I have a project for a client who is upgrading to Moodle 4.3 and is currently using this plugin. I will let you know as soon as I have some news.

Best regards,

Michael

**Comment by frederikmillingpytlick** [comment]
I've just tested the master branch on Moodle 4.3, it seemed to work

Closing issue
