### ISSUE TITLE
Sharing Cart is Partially available.

### ISSUE THREAD

**Issue by deepakbhalla-wd** [donhinkelman/moodle-block_sharing_cart#180]
Dear @donhinkelman,

At the outset, thank you for this awesome plugin. I hope this message finds you well. I'm reaching out to report a challenge we're encountering with the Sharing Cart plugin on Moodle 4.1.

Typically, our courses utilize the "Weekly Reverse Course Format," and we're aware that the Sharing Cart plugin sometimes encounters compatibility issues with this format. Our usual workaround is to switch to the standard "Weekly Format," which has consistently resolved the issue—until now.

In a recent course, even after switching to the standard "Weekly Format," the Sharing Cart is only partially functioning. The basket icon appears in the General section and the first two weeks of the course, but not beyond that.

I have attached a screenshot for your reference. Could you please provide guidance on resolving this issue?

Thank you for your support and the invaluable tool that the Sharing Cart is to our educational efforts.

Warm regards,

Deepak Bhalla

**Comment by donhinkelman** [comment]
Thank you, Deepak, for reporting this. Does it only happen with Sharing Cart 4.1 on Moodle 4.1?  You might try downloading Sharing Cart 4.3 which includes a number of updates by Anders of Moxis.

**Comment by deepakbhalla-wd** [comment]
Thank you for your prompt response and suggestion.

Upon reviewing our current setup, it appears that we have been utilizing Sharing Cart version 3.8 on our Moodle 4.1 platform. This mismatch may have contributed to the issues we're experiencing

We will proceed with upgrading to Sharing Cart version 4.3, as recommended, to take advantage of the updates and improvements

**Comment by donhinkelman** [comment]
Deepak, how did your upgrade to Sharing Cart 4.3 go?

**Comment by deepakbhalla-wd** [comment]
Thank you for asking. Our Sharing Cart plugin upgrade is on hold due to resource constraints with the festival season here. Expecting to get to it in the next 2-3 weeks. I'll keep you posted!

**Comment by AraPraxis** [comment]
Hello @deepakbhalla-wd 

Does everything work as expected or are there still issues with the plugin?

Kind regards,
Anders Rasmussen

Moxis Team

**Comment by donhinkelman** [comment]
Hi Deepak, any word if this problem persists?

**Comment by frederikmillingpytlick** [comment]
No response in a long time, closing issue.

Feel free to let us know if the issue still persist :)
