### ISSUE TITLE
Timeout when adding H5P to cart in Moodle 4.1.6

### ISSUE THREAD

**Issue by cdipe** [donhinkelman/moodle-block_sharing_cart#181]
We are using moodle 4.1.6, Sharing Cart 4.1, release 1, 2023032300
When adding a H5P activity to the cart it takes long time and ends with time out.

**Comment by donhinkelman** [comment]
Thank you for reporting this, cdipe. Could you upgrade to the latest Sharing Cart github version, and report if the problem persists?

**Comment by cdipe** [comment]
Hi @donhinkelman! I'll ask our server tech to put this on our test server. We have another problem with H5P that needs to be solved first, though.

**Comment by cdipe** [comment]
Hi @donhinkelman this solved the timeout!

**Comment by donhinkelman** [comment]
Thank you for closing this issue, Sam.
