### ISSUE TITLE
Feature: select any course as admin

### ISSUE THREAD

**Issue by stdoma** [donhinkelman/moodle-block_sharing_cart#197]
Hello!
The course search only finds entries to which you are assigned.
If you are logged in as an admin, it would be good if all courses could be searched and selected.
Otherwise you always have to log in as a specific person and log back into your normal account after work.

**Comment by frederikmillingpytlick** [comment]
The sharing cart have been completely reworked since this issue was reported, I will be closing the issue.

Feel free to let us know if you still have a feature request :)
