### ISSUE TITLE
Backup file not found because of itemid

### ISSUE THREAD

**Issue by Astor-Bizard** [donhinkelman/moodle-block_sharing_cart#199]
Backup files created by Sharing Cart block under the `files` database table, in user/backup area, now have `itemid` field referencing the `id` in `block_sharing_cart` table.
As convenient as it may be for this plugin, it breaks the computed file hash.
Files under user/backup area are expected to have itemid 0 by moodle (don't ask me why, this can be observed here: https://github.com/moodle/moodle/blob/7b172f51b99acfcaf2b2a2772617306a3bb36d9d/lib/filelib.php#L4852).
This makes trying to download these files from user private backup area impossible (as these files are not found, because they are searched for by hash).
The change seems to have been introduced by commit ec5a3d8 (in controller.php, line 382).

Note: this may also lead to backup files never being deleted, even when deleting activity from the Sharing Cart block.

**Comment by frederikmillingpytlick** [comment]
The sharing cart have been completely reworked since this issue was reported and we haven't had any similar issues so it would be hard for us to make a fix for this. Perhaps you could create a script to fix this on your site and then update the new sharing cart.

I will be closing the issue.
