### ISSUE TITLE
Feature Request: Sharing Cart Filenames

### ISSUE THREAD

**Issue by bfriesenvcc** [donhinkelman/moodle-block_sharing_cart#2]
This plugin is a _lifesaver_! We love it!  

It would be nice if the filenames included something in the name to make it clear that they are Sharing Cart files. Currently, the files sit mixed in with all the other User Private Backup files. A user who didn't know better, and wanted to clean up their files, could delete them by accident because they don't realize what they are.

**Comment by abias** [comment]
Hi @bfriesenvcc ,

I would be interested to understand your problem, can you elaborate please with Steps to reproduce and expected + actual results?

Thanks in advance,
Alex

**Comment by bfriesenvcc** [comment]
Hi, @abias 
It's pretty straight-forward. Currently when one copies to sharing cart, the backup files are stored under the "User private backup area," along with all of the customized backup files. Anyone cleaning up their backup area may accidentally delete these, not realizing that they are sharing cart files.

Steps to reproduce:
1) Visit a restore page and look under the User private back up area.
2) Note the last file created 
3) Go to a course page and copy anything to the sharing cart
4) Go back to the user private backup area (or refresh it)
5) Note the last file created. It should be the sharing cart item you just created.

My suggestion would be that the filename of the sharing cart item start with "sharingcart" or something like that, in the same way that the backup files start with "backup."

**Comment by abias** [comment]
Hi @bfriesenvcc ,

thank you for your detailed explanation. Now I see what you mean and I agree with you completely.

Thanks,
Alex

**Comment by donhinkelman** [comment]
Dear colleagues, I understand the problem. I have never "cleaned up" my backup area, but I see that some or many teachers may do that. This is a significant issue that will take some time to assess. I will work on approaches and get back to you later.

**Comment by johnnypraxis** [comment]
Fixed :-)
The files are now prefixed with "Sharingcart-" and the rest of the file name is lowercase.
