### ISSUE TITLE
Sharing Cart seem to mess with course section toggles

### ISSUE THREAD

**Issue by cdipe** [donhinkelman/moodle-block_sharing_cart#202]
Hi, we have recently noticed a strange fenomenon, that I'll try to descibe. The problem is not consistent, it doesn't happen all the time, but mostly.
After adding Sharing cart to a course, the section open/close toggle starts malfunctioning and all sections get collapsed with every page reload. 
This affects only the user having added the Sharing cart block; if another user visits the page, all works as expected. But, the problem sometimes "follows" the affected user into other courses, also in courses where there is no Sharing Cart block. This is not fully consistent, i. e. it doesn't happen in all courses. 

We have flushed our browser caches, that made no difference.
We have removed the Sharing Cart block, no difference.

Could this have anything to do with sessions?

We have also noted that after a few days the problem seem to disappears for the user, also in the courses where the Sharing Cart block was added. This too is not consistent; some of us still have the problem, but for me the problem has disappeared completely and when I add a Sharing Cart block to a new course there is no problem at all.

We have been using Sharing Cart since October 2023, when we upgraded to Moodle 4.1

**We are using Moodle 4.1.10 and Sharing Cart 4.1, release 1 2023032300**

**Comment by frederikmillingpytlick** [comment]
The sharing cart have been completely reworked since this issue was reported, I will be closing the issue.

Feel free to let us know if the issue still persist :)
