### ISSUE TITLE
Copy content issue on Moodle 4.4

### ISSUE THREAD

**Issue by RayCoSector** [donhinkelman/moodle-block_sharing_cart#203]
Hello,

We've noticed that the latest release has issues in Moodle 4.4 when you try and copy shared content back into another course when using 4.4, release 3 (2024020501)

On Copying content:
![image](https://github.com/donhinkelman/moodle-block_sharing_cart/assets/135825482/d4076ec8-df5a-4b50-8c80-04c12c626e83)

Item appears in Sharing Cart:
![image](https://github.com/donhinkelman/moodle-block_sharing_cart/assets/135825482/05525277-caa2-43cb-832d-de1b0e851816)

Navigate to another course & Click copy to course. The top menu appears, but there is no dotted box to indicate where the item should be copied to:
![image](https://github.com/donhinkelman/moodle-block_sharing_cart/assets/135825482/a80eb448-120c-47d2-99c6-acefadb5a94a)

Does anyone know a fix for this ?
Will this be fixed when version 4.5 lands - any updated news on when this might be ?

Regards,
Ray Reid.

**Comment by aspark21** [comment]
@donhinkelman i can get one of our devs to look at this in the coming week but would it be worth them looking at basing this on your dev branch?

**Comment by RayCoSector** [comment]
We've had this fixed for one of our customers and they would like to share with the community.

https://github.com/donhinkelman/moodle-block_sharing_cart/pull/204

Regards,
Ray Reid.

**Comment by leonstr** [comment]
It looks like this is a result of [MDL-74778](https://tracker.moodle.org/browse/MDL-74778) which removed course formats' format.js files which described each format's section containers. Replacing `M.course.format.get_section_wrapper()` -- broken by MDL-74778 -- with `'li.section'` resolves the issue but hopefully there's a dynamic way to obtain this as hard coding this value may not work with all supported course formats, or future changes to course formats.

**Comment by frederikmillingpytlick** [comment]
The sharing cart have been completely reworked since this issue was reported, I will be closing the issue.

Feel free to let us know if the issue still persist :)
