### ISSUE TITLE
Is async_copy_item.min.js being used?

### ISSUE THREAD

**Issue by leonstr** [donhinkelman/moodle-block_sharing_cart#205]
In `amd/build` there's `async_copy_item.min.js` and `async_copy_item.min.js.map`. However in `amd/src` there's no `async_copy_item.js`.

I can't see that the minified code is called anywhere.

Presumably either: 1) the above files should be removed if they're not being used, or 2) if they are being used `amd/src/async_copy_item.js` needs adding.

These files were added in commit 926ef11.

**Comment by frederikmillingpytlick** [comment]
The sharing cart have been completely reworked since this issue was reported and the files are no longer present, I will be closing the issue.

Thanks for letting us know :)
