### ISSUE TITLE
Missing defined('MOODLE_INTERNAL') || die();

### ISSUE THREAD

**Issue by OlenaTatarintseva** [donhinkelman/moodle-block_sharing_cart#22]
It looks like defined('MOODLE_INTERNAL') || die(); is missing in following files:

* classes/controller.php
* classes/exception.php
* classes/record.php
* classes/renderer.php
* classes/scoped.php
* classes/section_title_form.php
* classes/storage.php
* block_sharing_cart.php

Best regards,
Olena Tatarintseva

**Comment by johnnypraxis** [comment]
This bug has been fixed in the master branch:
https://github.com/donhinkelman/moodle-block_sharing_cart/commit/68161fa7609a419d1e95a2975d1d62e026370c68
