### ISSUE TITLE
Moodle 4.2 and master branches are missing proper privacy provider implementation

### ISSUE THREAD

**Issue by golenkovm** [donhinkelman/moodle-block_sharing_cart#220]
It looks like [MOODLE_42_STABLE](https://github.com/donhinkelman/moodle-block_sharing_cart/blob/MOODLE_42_STABLE/classes/privacy/provider.php) and [master](https://github.com/donhinkelman/moodle-block_sharing_cart/blob/master/classes/privacy/provider.php) branches are missing the privacy provider implementation that [MOODLE_41_STABLE](https://github.com/donhinkelman/moodle-block_sharing_cart/blob/MOODLE_41_STABLE/classes/privacy/provider.php) has.

As a result, core `test_all_providers_compliant`unit test is failing on this:
```
2) core_privacy\privacy\provider_test::test_all_providers_compliant with data set "block_sharing_cart" ('block_sharing_cart', 'block_sharing_cart\privacy\provider')
Failed asserting that false is true.

/var/www/site/privacy/tests/privacy/provider_test.php:179
/var/www/site/lib/phpunit/classes/advanced_testcase.php:76
```

**Comment by golenkovm** [comment]
Thanks heaps @frederikmillingpytlick and @donhinkelman

**Comment by frederikmillingpytlick** [comment]
@golenkovm fixed in https://github.com/donhinkelman/moodle-block_sharing_cart/pull/221 :)
