### ISSUE TITLE
Stille encounter: https://github.com/donhinkelman/moodle-block_sharing_cart/issues/11?_pjax=%23js-repo-pjax-container

### ISSUE THREAD

**Issue by neeesn** [donhinkelman/moodle-block_sharing_cart#23]
We still encounter the same issue as described in https://github.com/donhinkelman/moodle-block_sharing_cart/issues/11?_pjax=%23js-repo-pjax-container

We stille have this issue - we have updated sharing_cart to version 2019012000 3,6 Release 1
We are currently using moodle 3.4.3+

**Comment by TubsDK** [comment]
This has been fixed in the latest commits.
