### ISSUE TITLE
Javascript Caching causes buttons to freeze in 3.6-3.8

### ISSUE THREAD

**Issue by donhinkelman** [donhinkelman/moodle-block_sharing_cart#31]
The first testing in Moodle 3.8 shows this issue reported by Osvaldo in the [Plugins Database Forum](https://moodle.org/plugins/block_sharing_cart):

> "Just updated to moodle 3.8 and sharing cart is not working. More exactly, every time we turn edition on, all edition button freezes. Then, if we purge all caches and return to course, that's ok. But if in sequence we turn edition off and on again, the freezing problem returns.

I have asked Osvaldo to provide the theme used when this issue appears.

**Comment by canatojr** [comment]
Ok, here it is!

The problem seens to be the same in all themes. Tested is Boost, Adaptable and Classic. Also tested in different browsers.
A detail that I just discover is that we don't need to purge all caches but only the JavaScript cache.

**Comment by canatojr** [comment]
I found that  a temporary solution is to leave javascript caching disabled. 
But moodle team advise: "_Javascript caching and compression greatly improves page loading performance. it is strongly recommended for production sites_."

**Comment by kdidier51** [comment]
I have the same problem. "More exactly, every time we turn edition on, all edition button freezes. Then, if we purge all caches and return to course, that's ok. But if in sequence we turn edition off and on again, the freezing problem returns". The problem seems to be the same in all themes.

**Comment by canatojr** [comment]
Glad to report that the issue was solved once done the moodle update to 3.8.1 version!

**Comment by donhinkelman** [comment]
Dear Canatojr, Thank you very much for your testing and re-testing. Let me confirm. The Sharing Cart problems occured in Moodle 3.8.0. But those same problems disappeared after upgrade to Moodle 3.8.1. Is that correct? And do you know what in 3.8.1 caused that fix to happen?

**Comment by canatojr** [comment]
Hello Don!
Yes, after upgrade to Moodle 3.8.1, those problems disappeared.
Remember some days ago I found a temporary solution about turning off the JavaScript cache?
So, I guess Moodle 3.8.1 bring some modification in its JavaScript cache code.

**Comment by kdidier51** [comment]
Hi Don,
With a Moodle 3.8.1+ (02.14.2020) and the plugin 3.6 release 2 (2020021000) and EDGE, all is Ok. 
But the problem is Always the same with Firefox and Chrome. I Don't use the canatojr's solution : turning off the Javascript cache. 
So, for the moment, I only use EDGE for Moodle. 
Sincerely

**Comment by donhinkelman** [comment]
I found another problem when using Sharing Cart 3.8, release 1 in Moodle 3.8.1+.  The "Copy to Sharing Cart" icon in the dropdown menus does not appear, both in Firefox and Chrome browsers. I have alerted Praxis developers, and they replied they will fix it asap.

**Comment by Roussxx** [comment]
Hi,
Same issue in Moodle 3.8.2 with SC 3.8 release 2.
**When edition turned on, all section's edition button freezes.** need to purge the caches to recover the buttons.
Please note that the problem appears after the upgrade from 3.6, release 1 2019012000 to 3.8 release 22020032600 (version with kart icon)

**Comment by Roussxx** [comment]
Just add that, as mentionned before, leave javascript caching disabled solves the problem.

**Comment by donhinkelman** [comment]
Thank you Roussxx, for reporting the issue, which confirms what kdidier and canato earlier found. I have renamed the issue to be more specific, and will ask Praxis to work on this. Note to all, if you experience this problem, the workaround is to disable javacript scripting.

**Comment by Roussxx** [comment]
Hi,
Just to advise that javascript caching issue still here with Sharing Cart 3.8, release 3.
thks

**Comment by kdidier51** [comment]
Hi,
I confirm. All is Ok for the first time and then, buttons and "Insert a new activity" don't  work. 
In June, July and August, teachers used very much Sharing cart for the new courses. Import is not so easy than sharing_cart. 
Thanks for futur good news ...

**Comment by plourdej228** [comment]
Hi
I have Moodle 3.8.3 and sharing_cart 3.8 release 3 2020041200 and I have the problem.  If I disable the Java caching it's ok.
Thanks.

**Comment by Mikkeljeppesen1** [comment]
@canatojr @kdidier51 @plourdej228 @donhinkelman 

I just made a new moodle site version 3.8.3+ (build: 20200522) with sharing cart version 2020041200, and tested it in firefox and chrome without any problems with freezing buttons or the dropdowns. I have javascript caching on and didnt purge any caches. Have one of you tried to first disabled javascript caching and then enable it again. When you do that it will rebuild the cache and may help. Please update your sharing cart to the newest version, and let me know the outcome

**Comment by kdidier51** [comment]
Hello,
I have tried on my test platform and done : first disabled javascript
caching and then enable it again.
But, that does not work.
There is always a big red error message  on the console (F12). i have the
latest version. This message is present only on the course where Sharing
cart is installed.
  If javascript caching is disabled, it's good, but some functionality is
disrupted.
If you want, I can give you a login and password to see on my test platform.
Sorry.
And excuse me for my poor English.
Best regards
Didier CABY (France)

**Comment by plourdej228** [comment]
Hi
I made a test too.
I purge all the cache, I Turn editing on and it's ok.   I turn off editing and i turn on again and it doesn't work.

I also see an error in the console when the bug occurs.
[error.log](https://github.com/donhinkelman/moodle-block_sharing_cart/files/4691209/error.log)

I'm from Quebec and I speak french so my English is not very good.

Thanks for the support.

**Comment by donhinkelman** [comment]
Thank you all for your persistent reporting of the javascript issue. It is beyond my understanding and I hoped by ignoring it, it would go away. ;-)  So, why am I not experiencing this freezing problem?  I checked with my school's server admin, and he showed me that Moodle caching system is rather complex.  Much more than just "Javascript caching" enabled/unenabled (our server has Javascript enabled in the main setting).  However, when you look here, you see that there are seven different caching systems, and according to him, the Redis caching is one related to javascript.
<img width="737" alt="Screen Shot 2020-05-28 at 11 13 58" src="https://user-images.githubusercontent.com/12912710/83091516-4d62fd80-a0d6-11ea-9a02-44fd90095746.png">
However, notice that while the Redis has a green check mark, but the store is listed as zero (0). This means there is no caching happening. My engineer was surprised to discover this, and immediately tried to turn it on, because our Moodle 3.8 was running slow. He could not immediately fix it, so I will report later what happens. For now, please check your server setting and see if your Redis has a Store= 1 setting. That is what we are trying to do. 
 By the way, I am from Hokkaido, Japan and although I am an English teacher, my English is not very good. :-)  Thank you for kindly working in a foreign language to solve this problem.

**Comment by Mikkeljeppesen1** [comment]
Hey guys,

Found the problem on moodle (tracker https://tracker.moodle.org/browse/MDL-67327). 

If you read the thread, you will see that the problem seems to be with the plugins you have installed and not with the moodle. I think thats why Don Hinkelman and i dont get any problem with freezing elements.

Everone with the problems: please read the thread to get more information about it.

**Comment by donhinkelman** [comment]
Hi Mikkel, thanks for checking that out. I see two plugins mentioned: qtype_wordselect and mod_treasurehunt from the plugins database.  How about Didier and Lourde? Do you use those plugins?  Or other plugins that might be suspect?  For your information, here at my school, our engineer re-installed the Redis cache to Store = 1. No Sharing Cart problems followed. So

**Comment by donhinkelman** [comment]
``

**Comment by donhinkelman** [comment]
Oops, I hit the "Close" button by mistake. Let's see if removing suspect plugins will solve this issue.

**Comment by Mikkeljeppesen1** [comment]
Hi Don,
I haven't tested other plugins, and my knowledge about the "plugin problem" is from the tracker. None of the plugins we use on a daily basis have given us problems so far.

**Comment by Mikkeljeppesen1** [comment]
Hey Didier,

Sorry to hear about your problems. I have posted a link in the GitHub issue thread that might help you. Shortly said, I found on moodle tracker, some guys with the same project. It says that it was other plugins there was the problem. I will link to the solution thread below or try to make a new test platform with only moodle and sharing cart installed and see if you still got problems. No matter what, please let me know.

The link to moodle tracker solution:
https://tracker.moodle.org/browse/MDL-67327


Best regards
Med venlig hilsen
Mikkel Jeppesen
Udvikler
[cid:image001.png@01D634DA.8BE9D280]<https://praxis.dk/>
PRAXIS
HOVEDKONTOR: Munkehatten 28, 5220 Odense SØ
KØBENHAVN: Ny Vestergade 17,4, 1471 Kbh. K
AABENRAA: Sct. Nicolai Gade 5, 1. tv, 6200 Aabenraa
Tlf. +45
 · praxis.dk<http://www.praxis.dk>
Følg os på Facebook<https://www.facebook.com/EF.NTF?ref=hl> og LinkedIn<http://www.linkedin.com/company/erhvervsskolernes-forlag?trk=tyah&trkInfo=tarId%3A1415274383712%2Ctas%3Apraxis+-+erh%2Cidx%3A1-1-1>
Tilmeld dig vores nyhedsbrev<http://www.us3.list-manage.com/subscribe?u=0aee24e00a3e58ddad6c0bf89&id=41e222f959>
Erhvervsskolernes Forlag, Nyt Teknisk Forlag og itai er blevet til: PRAXIS
Vi leverer fortsat læremidler, fagstof og digitale løsninger i høj kvalitet.

Fra: Didier <notifications@github.com>
Sendt: 27. maj 2020 10:55
Til: donhinkelman/moodle-block_sharing_cart <moodle-block_sharing_cart@noreply.github.com>
Cc: Mikkel Jeppesen <mje@praxis.dk>; Comment <comment@noreply.github.com>
Emne: Re: [donhinkelman/moodle-block_sharing_cart] Javascript Caching causes buttons to freeze in 3.6-3.8 (#31)

Hello,
I have tried on my test platform and done : first disabled javascript
caching and then enable it again.
But, that does not work.
There is always a big red error message on the console (F12). i have the
latest version. This message is present only on the course where Sharing
cart is installed.
If javascript caching is disabled, it's good, but some functionality is
disrupted.
If you want, I can give you a login and password to see on my test platform.
Sorry.
And excuse me for my poor English.
Best regards
Didier CABY (France)

**Comment by plourdej228** [comment]
I don't use the plugins qtype_wordselect and mod_treasurehunt.
For now I don't have a Redis cache.
I will continue searching if I find another plugin causing problem.

**Comment by plourdej228** [comment]
Hi, I have found a theme in my Moodle causing problem.   It's "home-made" theme use in Schoolboard in Quebec.  We'll communicate with the authors to see if they can fix this problem.

Thanks.

**Comment by donhinkelman** [comment]
Thanks for checking that out. Custom themes are often a problem. The Sharing Cart is tested in Moodle standard themes, and we ask custom theme developers to help make it compatible with their themes. Is it OK to close this issue?

**Comment by plourdej228** [comment]
For me it's ok.

**Comment by Mikkeljeppesen1** [comment]
@donhinkelman it's okay for me too

**Comment by donhinkelman** [comment]
OK, I will close this issue, and put new version of Sharing Cart 3.8 release 10 on the plugins database. Feel free to ask to reopen this issue if we find this problem returning.
