### ISSUE TITLE
Menu Item Missing from Sections with Collapsed Topic Format

### ISSUE THREAD

**Issue by bfriesenvcc** [donhinkelman/moodle-block_sharing_cart#32]
When using the _Collapsed Topic_ course format, the SC menu option is missing from all of my *sections* containing any resources and activities and instead appears at the bottom of the edit menu for the first resource or activity. In empty sections, it appears where expected - on the menu for the section. This problem doesn't occur when I use a different course format, so the problem my lie there.  I'm using version 3.6, release 1 2019012000, in Moodle 3.6.6.

In this image, you can see the double occurance of the SC option on the edit menu for the first activity in the section. Trust me when I say that the menu option is missing from the section's edit menu. :-)

<img width="627" alt="DoubleSC" src="https://user-images.githubusercontent.com/8193384/72648885-12cfa400-3931-11ea-87a2-b0a1e3372f33.PNG">

**Comment by Mikkeljeppesen1** [comment]
@bfriesenvcc 

Do you still see this bug? If you do, please update sharing cart to the newest version, and then the duplicate "copy to sharing cart" bug should be gone. If this doesn't help please let me know

**Comment by Mikkeljeppesen1** [comment]
@donhinkelman 

I think we should close this one. We cant recreate the problem and no answer at all.

**Comment by donhinkelman** [comment]
I agree. To bfriesenvcc, please upgrade to latest Sharing Cart on github and see if there are any issues.

**Comment by bfriesenvcc** [comment]
OMG, guys, I'm sorry! I don't know why I didn't see this or respond. We have upgraded to the newer version and all is well. 
My apologies, once again.
