### ISSUE TITLE
Bug with REMUI theme: Coping section to Sharing Cart throw exception

### ISSUE THREAD

**Issue by YogevBokobza** [donhinkelman/moodle-block_sharing_cart#34]
Hi,

I'm having problem with Sharing Cart and REMUI theme.
When I'm trying to copy complete section to Sharing Cart I get exception (picture attached).
The exception says that "A required parameter (sectionid) was missing".

I found the reason for that.
I saw that you are trying to get the sectionid by searching the HTML looking for h3 title.
However, In REMUI theme (at least in my current version which is: 3.7.3) they use h4 for title.
So Sharing Cart can't find sectionid and exception is thrown.

Possible fix I found:
In file: `blocks/sharing_cart/script.js`
In line: `1141`
Change from:`var sectionID = $(this).find("div.content h3.sectionname span.inplaceeditable").attr("data-itemid");`
To:` var sectionID = $(this).find("div.content .sectionname span.inplaceeditable").attr("data-itemid");`

Mainly fix is that to remove h3 reference and leave just .sectionname class.
 
This fix also can solve the problem in other themes (if there any).

thanks,
Yogev.

![pic](https://user-images.githubusercontent.com/22839127/73457284-1b39cd00-437c-11ea-87b0-26d98d5d32b3.png)

**Comment by DKSteffensen** [comment]
Hey,

We are working with this in Praxis, and would like to know which versions you are using.
Please tell us your:
REMUI version, MOODLE version and most important sharing_cart version.

The code you posted, is not the same as seen in the master branch, so maybe the issue has been resolved? 

Please provide us with as much information, and we will look into it.

**Comment by DKSteffensen** [comment]
Just want to follow up on this, and hear if you still got this issue? @YogevBokobza

**Comment by Mikkeljeppesen1** [comment]
@donhinkelman 

Can you close this one - we soved it long time ago

**Comment by donhinkelman** [comment]
Thank you for taking care of this before.
