### ISSUE TITLE
UI improvements to match moodle standards better.

### ISSUE THREAD

**Issue by DKSteffensen** [donhinkelman/moodle-block_sharing_cart#37]
UI improvements:
 * Icons should be converted to font-awesome.
 * Dropzones for moving are just empty white spaces.
 * Match dropzones when copying activity to section.
 * When expanding folders, it's hard to see which files belong there.
 * Labels with images don't resize and just add the fullsize image.
 * Alerts/Confirm boxes should be modals.
 * Bulkdelete could use a layout overhaul.
 * Loading boxes should match moodle better.

Bug fixes:
 * When changing groupmode, or duplicating activity, the sharing cart icons disappear.
 * PHP warning when adding activity to a subfolder, of an empty folder.
 * Sometimes unable to delete folders, due to duplicate names and no user check.

New features:
 * Copy section dropdown in the block, due to some course formats preventing sharing cart from adding icons.

**Comment by donhinkelman** [comment]
Ambitious improvements listed. Thank you for your attention to these details.

**Comment by donhinkelman** [comment]
The new UI looks great, Daniel. A small request is to make the icons inside the Sharing Cart more separated, when using the Firefox browser. The same icons look nicely separated in the Chrome browser.

**Comment by Mikkeljeppesen1** [comment]
@donhinkelman 

I don't know where you want the icons to be more separated? Can you send a screenshot, so I can fix it
