### ISSUE TITLE
Version naming not correct or file not correct

### ISSUE THREAD

**Issue by JamesRussellCGPS** [donhinkelman/moodle-block_sharing_cart#4]
Version 3.5 is showing as 3.3 release 3 with version number 2018012400. The README is showing 3.3 information as well. Is it actually updated?

**Comment by abias** [comment]
Hi @JamesRussellCGPS ,

I assume that https://github.com/donhinkelman/moodle-block_sharing_cart/commit/1f6e45b9d4ef50454efdf61e20f1dd373bac71b5 fixed this issue and it can be closed.

**Comment by donhinkelman** [comment]
Thanks, Abias, and this issue is closed.
