### ISSUE TITLE
error/setting_locked_by_config (??)

### ISSUE THREAD

**Issue by besauer** [donhinkelman/moodle-block_sharing_cart#42]
Hi there,
I already installed your plugin on several servers. All users really enjoy working with your tool. It makes collaboration soy easy. I love it!
Today I tried to install the plugin on an other machine. That worked fine. 

But now I'm gettin an error I realy don't understand: error/setting_locked_by_config

Roles are set up properly.

Do you have any ideas?

**Comment by donhinkelman** [comment]
Thank you for reporting this issue you are having with one server. As I understand, this error only appears on the new server that you installed it on. Is that correct?  So the other servers do not have this problem.  Perhaps it means that your server settings are locked somewhere--this might involve the Moodle core file, config.php.  Could you do a little more research, such as this Tracker issue: https://tracker.moodle.org/browse/MDL-42999.   Or you could turn on full debugging for your site and see if more extensive error messages appear?  I assume you are using Moodle 3.8 with the latest Sharing Cart code.

**Comment by besauer** [comment]
Yes. The problem only appears on one server. The others are working fine. The moodles version is 3.7.6+.

1.) click on activity-settings
2.) click  on "Copy to sharing-cart"
3.) confirm to copy users-data
4.) confirm "Do you want to copy to sharing-cart"
5.) I can see 1 sec. an rotating loading image
6.) the Error: error/setting_locked_by_config appears

There are no error messages in Debug mode.

**Comment by johnnypraxis** [comment]
Hi besauer

I tried installing the latest version of the Sharing Cart on a Moodle 3.7.6+ and I can't reproduce the error.

First of all install the latest version of the Sharing Cart on your site.

1) Try to duplicate the activity. If that's not possible it probably doesn't have anything to do with the Sharing Cart.
2) You could also try to copy the entire course to another location using the built in backup/restore function in Moodle and see if that's possible.
3) It could be related to your cron jobs as well. Avoid calling them or try disabling them one at the time and see if you are able to copy the activity afterwards.

**Comment by gurviche** [comment]
I have recently encounter with the same problem. It appears backup controller is trying to force some backup plan settings and is generating the exception if one of this settings is locked in general backup configuration. The problem is the error is generating even if the locked value is the same as one which controller is trying to set. I did a small patch which fixed a problem for me (Pull request #54 )

**Comment by donhinkelman** [comment]
Thank you, gurviche, for providing a solution to this problem. Johnny, could you try this patch?  I am not knowledgeable enough to judge whether to merge this pull request.

**Comment by johnnypraxis** [comment]
Unfortunately the pull request from gurviche did not fix the issue. I fixed the issue in the pull request below instead by not copying locked settings:
https://github.com/donhinkelman/moodle-block_sharing_cart/pull/58

**Comment by donhinkelman** [comment]
I see. And really appreciate your vigilance.
