### ISSUE TITLE
"copy to sharing cart" option completely dissappears with Grid courseformat

### ISSUE THREAD

**Issue by Urpokarhu1** [donhinkelman/moodle-block_sharing_cart#48]
Sharing cart dissappears from settings-menu when you delete general section that has been moved in to the Grid in Grid-courseformat. See attached video. 

[sharingbug.zip](https://github.com/donhinkelman/moodle-block_sharing_cart/files/4835406/sharingbug.zip)

Steps to repeat:

1. Create a new course in Grid format with default settings
2. In the General section click "move section into grid"
3. Check that General-section edit menu has "copy to sharing cart" (for some reason it has two menuitems there)
4. Delete General-section
5. Check that general section has "copy to sharing cart"
6. Refresh the webpage
7. Notice that General section or any other section doesn't have anymore "copy to sharing cart" option available and you cannot restore them.

tested with Moodle 3.5 & format_grid 3.5.0.6 (2018052306) & block_sharing_cart 3.3, release 3 (2018012400)

**Comment by donhinkelman** [comment]
Thanks, Urpokarhu. I really appreciate the methodical notes you sent to show the problem and the clear screencast video you sent. That's the good news. The bad news is I am not a programmer and the volunteer programmers who work on the Sharing Cart only have time for standard themes and standard course formats. We have also upgraded Sharing Cart to 3.8.10 and wish you could upgrade your Moodle to take advantage of the new layout and all the bug fixes that went into it. I wonder if anyone else using the Grid format has had better SC performance in Moodle 3.8?

**Comment by Urpokarhu1** [comment]
Hello,

Sharing cart has changed in version 3.8 completly and it works with Grid course format because section copy have been moved from under menu to the block itself.

**Comment by donhinkelman** [comment]
Well, that is wonderful news, Urpokarhu. I hope you can use Sharing Cart 3.8 on your Moodle 3.5 site.

**Comment by donhinkelman** [comment]
I am closing this issue. Thanks for reporting the original problem and how it was solved.
