### ISSUE TITLE
Error with "Copy to Course" in 3.9

### ISSUE THREAD

**Issue by bfriesenvcc** [donhinkelman/moodle-block_sharing_cart#50]
I've just installed on our 3.9 development server (see below for more environment information) and am experiencing the following:

The copy to sharing cart functions as expected. However, when I try to copy to course, I get an error message when clicking on "Copy here" anywhere in the course. 

"can't currently handle this request. HTTP ERROR 500"

Here is the debugging info:
This page should be using theme clean which cannot be initialised. Falling back to the site theme boost
line 687 of /lib/outputlib.php: call to debugging()
line 7480 of /lib/moodlelib.php: call to theme_config::load()
line 1158 of /backup/util/dbops/restore_dbops.class.php: call to get_list_of_themes()
line 1144 of /backup/moodle2/restore_stepslib.php: call to restore_dbops::create_included_users()
line 34 of /backup/util/plan/restore_execution_step.class.php: call to restore_create_included_users->define_execution()
line 181 of /backup/util/plan/base_task.class.php: call to restore_execution_step->execute()
line 178 of /backup/util/plan/base_plan.class.php: call to base_task->execute()
line 168 of /backup/util/plan/restore_plan.class.php: call to base_plan->execute()
line 384 of /backup/controller/restore_controller.class.php: call to restore_plan->execute()
line 482 of /blocks/sharing_cart/classes/controller.php: call to restore_controller->execute_plan()
line 112 of /blocks/sharing_cart/restore.php: call to block_sharing_cart\controller->restore()

Fatal error: Class 'backup_execution_step' not found in /data/shares/vcc/moodle-3.9/backup/moodle2/backup_stepslib.php on line 33

I have tried copying previously existing items, as well as newly created ones, with the same results.
Thinking that something had become corrupt on our DEV server, I tried uninstalling the plugin, but get a timeout error. So I decided I would fudge it and bump up the version to 801 so that I could "update" it. The update worked fine, but the problem still exists.

This could totally be a problem on our end, because we're having all kinds of little wonky things going on.

Environment:
Version: 3.9+ (2020061500.04)
Release: 07.04.2020
PHP: 7.2.31-1+ubuntu16.04.1+deb.sury.org+1
MySQL: 5.7.29-0ubuntu0.16.04.1
Theme: Boost
Course format: All formats
Browsers: All (Chrome, Firefox, Opera, Vivaldi)

**Comment by bfriesenvcc** [comment]
I just installed the latest version of Moodle, on my local computer, and I don't experience the same issue, so I really have no idea.

**Comment by bfriesenvcc** [comment]
I'm getting desperate for ideas. We're upgrading to Moodle 3.9 in 2 days.

**Comment by johnnypraxis** [comment]
Hi bfriesenvcc

First of all. The clean theme is not installed in Moodle 3.9. You probably got that theme activated in an earlier version of Moodle and now it can't be found. Go to your theme settings and switch to the boost theme:
Site administration => Appearance => Theme selector => Change theme

I just installed the latest version of Moodle 3.9 on my development environment and I can't reproduce the error. The Sharing Cart works fine here.

I see the "backup_execution_step" class can't be found. The location of the file with the class should be:
/backup/util/plan/backup_execution_step.class.php

Add the file if it's not there already. Just take it from the ZIP with the files for your Moodle version from moodle.org.

This issue could be related to the autoloader in Moodle as well. The location of all classes in Moodle are stored in the class map cache. Try to purge the cache in Moodle to update the class map cache and hopefully solve the issue if the class path is not up to date. Make sure the above file exists before doing so.

**Comment by bfriesenvcc** [comment]
Hi, Johnny. Thank you for your reply. SPOILER ALERT: No longer a problem.

Although the message refers to the clean theme, we do not have it installed, and we are using Boost. I don't know why the message states, "This page should be using theme clean" but I do know why it "cannot be initialised."

All of the files were there, as expected and I even examined them to ensure that they were exactly the same as on my local installation, which was working.

As far as the issue itself, it appears to have resolved itself in our Production system. So, there is something wonky with our Development site, which hopefully we'll figure out one day. In the mean time, this appears to be resolved.

Thanks for your time.
