### ISSUE TITLE
Moodle 3.9 Copy to course generates a blank screen and hang

### ISSUE THREAD

**Issue by AndrewBrooks56** [donhinkelman/moodle-block_sharing_cart#60]
Turn editing on->Add a block->Sharing Cart
select Copy to course->select Copy here under Topic 1
select Change section title to "xxx"->select Continue
*** BLANK SCREEN *** and hang at this URL:
~/blocks/sharing_cart/restore.php 
without logging in, this URL points to the missing parameter error:
https://docs.moodle.org/39/en/error/moodle/missingparam

**Comment by donhinkelman** [comment]
Hi Andrew. Thanks for reporting your issue. I tried to duplicate the error in Moodle 3.9 in Firefox 80.0, Classic theme. I did not get the error you reported when I tried to copy a section into the Sharing Cart 3.8 release 10. I got another error: **undefined - Error**
<html> <head><title>504 Gateway Time-out</title></head> <body bgcolor="white"> <center><h1>504 Gateway Time-out</h1></center> </body> </html>   ThenCould give more data about the theme you are using?

**Comment by AndrewBrooks56** [comment]
Moodle theme - Boost
Sharing Cart - 3.8, release 10
I can add to the Sharing Cart OK, but cannot Copy to course - error as noted above

**Comment by donhinkelman** [comment]
Hi Andrew, do you still get this blank screen after upgrading to Sharing Cart 3.9, release 3?
