### ISSUE TITLE
In Moodle 3.9 Topics/Weekly formats, section copy fails

### ISSUE THREAD

**Issue by james-cnz** [donhinkelman/moodle-block_sharing_cart#61]
In Moodle 3.9 Topics or Weekly formats, when attempting to copy a section to Sharing Cart (unless sections have recently been moved by drag and drop), an error is displayed:
undefined - Error
A required parameter (sectionname) was missing

It seems that in the Sharing Cart function backup_section() there is a line:
var sectionName = $commands.closest('li.section.main').attr('aria-label');
This attempts to extract the section name from the section's aria-label property.
Moodle 3.9 Topics and Weekly formats have replaced the aria-label property with aria-labelledby--MDL-68189.
(The aria-label currently gets added back in when moving sections with drag and drop though--MDL-69637.)
In Moodle 3.8 and earlier, the aria-label property remains, and aria-labelledby hasn't been added.

Perhaps it would make sense to extract the section name from the the text in the section's H3.sectionname tag instead?

**Comment by ahruska** [comment]
Hi!

We also have this issue in one of our instances - the fix to adress the lables correctly shold not be too difficult and we would appreciate  a quick solutions so we do not have to patch and then repatch ;-)

Thanks in advance!

Andreas

**Comment by donhinkelman** [comment]
Thank you James and Ahruska for reporting this issue in Moodle 3.9 Topics and Weekly format. Could I confirm the Moodle theme and browser used when you experienced the problem?  I will initially assign our colleagues in Praxis to this.

**Comment by james-cnz** [comment]
Hi Don,
I believe I probably would have been using Boost for the theme, and Firefox for the browser.  (I'm not in at work at the moment to check, but that's what I usually use.)  However I'm pretty sure this will apply regardless of theme or browser.  It looks like it's due to a change in moodle/course/format/renderer.php function section_header() made between Moodle 3.8 and Moodle 3.9, specifically the replacement of the 'aria-label' property with 'aria-labelledby'.
Cheers,
James

**Comment by james-cnz** [comment]
I've now tried in Boost and Classic themes, and Chrome, Edge, and Firefox browsers, and all have this issue.
It looks like it can be fixed by changing script.js function backup_section() line:
  var sectionName = $commands.closest("li.section.main").attr('aria-label');
to:
  var sectionName = $commands.text().trim();

**Comment by james-cnz** [comment]
Hi Don and Jonny,

It looks like I inadvertently had an old version of Sharing Cart installed.  (I used the Site administration > Plugins > Install plugin feature in Moodle 3.9 on my test server, but I also have Moodle 3.5 installed on the same server, and that seems to have confused the Install plugin feature.)  The current version of Sharing Cart doesn't produce this error for me.

Andreas, I don't suppose you also have an old version of Sharing Cart installed on Moodle 3.9?

**Comment by frederikmillingpytlick** [comment]
Hi @ahruska, does this issue still persist?

**Comment by Astor-Bizard** [comment]
Hi,

I also have this problem, Moodle 3.9 / Sharing Cart 3.10 (2021092900, 3.10 release 8).
Theme Boost, on Firefox.

When I reload the course page after the error occured, the section has been copied to the Sharing Cart, but it doesn't display the section name (it displays a number between parenthesis, like (1) or (8)).

**Comment by donhinkelman** [comment]
Astor-Bizard, thank you for reporting your experience. I hope Frederik has time to look into this issue.

**Comment by Astor-Bizard** [comment]
On amd/src/script.js, the way the section name is retrieved (via aria-label attribute) seems to be the problem.
A fix that works on my side is to replace both lines 370 and 1151 :
`var sectionName = $section.attr('aria-label');`
by
`var sectionName = $section.attr('aria-label') || $section.find('.sectionname').text().trim();`
As far as I can test it, it solves the problem and works for Moodle 3.6 to 3.11, at least.

**Comment by donhinkelman** [comment]
Thank you, Astor-Bizard, for creating a code fix for this issue. If you can make a pull request of this code and I will approve it.
