### ISSUE TITLE
Moodle 3.9 PostgreSQL Can't Restore

### ISSUE THREAD

**Issue by coryarobbins** [donhinkelman/moodle-block_sharing_cart#62]
Hello,

The sharing cart had been working fine in 3.8 and MySQL.  I migraged the site to a new server, changed the database backend to PostgreSQL, and updated to 3.9.  Things are working as expected except for the sharing cart...  I can do a normal course restore, and I can do an import as well as a direct course copy, but any of the items I have tried to add to and then import from the sharing cart result in an error.  I don't have the slightest idea on where to start...  Here is the trace...

dml_read_exception: Error reading from database (ERROR: invalid input syntax for type bigint: "" SELECT * FROM mdl_backup_ids_temp WHERE backupid = $1 AND itemname = $2 AND itemid = $3 [array ( 0 =&gt; '3aa2e54c03ae6a1a89bfd90d4b429c6e', 1 =&gt; 'course_module', 2 =&gt; '', )]) in [dirroot]/lib/dml/moodle_database.php:486 Stack trace: #0 [dirroot]/lib/dml/pgsql_native_moodle_database.php(329): moodle_database-&gt;query_end() #1 [dirroot]/lib/dml/pgsql_native_moodle_database.php(920): pgsql_native_moodle_database-&gt;query_end() #2 [dirroot]/lib/dml/moodle_database.php(1624): pgsql_native_moodle_database-&gt;get_records_sql() #3 [dirroot]/lib/dml/moodle_database.php(1596): moodle_database-&gt;get_record_sql() #4 [dirroot]/lib/dml/moodle_database.php(1575): moodle_database-&gt;get_record_select() #5 [dirroot]/backup/util/dbops/restore_dbops.class.php(240): moodle_database-&gt;get_record() #6 [dirroot]/backup/util/dbops/restore_dbops.class.php(1737): restore_dbops::get_backup_ids_cached() #7 [dirroot]/backup/util/plan/restore_structure_step.class.php(219): restore_dbops::get_backup_ids_record() #8 [dirroot]/backup/util/plan/restore_structure_step.class.php(211): restore_structure_step-&gt;get_mapping() #9 [dirroot]/backup/moodle2/restore_stepslib.php(2691): restore_structure_step-&gt;get_mappingid() #10 [dirroot]/backup/util/plan/restore_structure_step.class.php(137): restore_badges_structure_step-&gt;process_parameter() #11 [dirroot]/backup/util/helper/restore_structure_parser_processor.class.php(121): restore_structure_step-&gt;process() #12 [dirroot]/backup/util/xml/parser/processors/grouped_parser_processor.class.php(178): restore_structure_parser_processor-&gt;dispatch_chunk() #13 [dirroot]/backup/util/helper/restore_structure_parser_processor.class.php(109): grouped_parser_processor-&gt;postprocess_chunk() #14 [dirroot]/backup/util/xml/parser/processors/simplified_parser_processor.class.php(148): restore_structure_parser_processor-&gt;postprocess_chunk() #15 [dirroot]/backup/util/xml/parser/processors/progressive_parser_processor.class.php(92): simplified_parser_processor-&gt;process_chunk() #16 [dirroot]/backup/util/xml/parser/progressive_parser.class.php(190): progressive_parser_processor-&gt;receive_chunk() #17 [dirroot]/backup/util/xml/parser/progressive_parser.class.php(278): progressive_parser-&gt;publish() #18 [internal function]: progressive_parser-&gt;end_tag() #19 [dirroot]/backup/util/xml/parser/progressive_parser.class.php(179): xml_parse() #20 [dirroot]/backup/util/xml/parser/progressive_parser.class.php(158): progressive_parser-&gt;parse() #21 [dirroot]/backup/util/plan/restore_structure_step.class.php(110): progressive_parser-&gt;process() #22 [dirroot]/backup/util/plan/base_task.class.php(181): restore_structure_step-&gt;execute() #23 [dirroot]/backup/util/plan/base_plan.class.php(178): base_task-&gt;execute() #24 [dirroot]/backup/util/plan/restore_plan.class.php(168): base_plan-&gt;execute() #25 [dirroot]/backup/controller/restore_controller.class.php(384): restore_plan-&gt;execute() #26 [dirroot]/blocks/sharing_cart/classes/controller.php(482): restore_controller-&gt;execute_plan() #27 [dirroot]/blocks/sharing_cart/restore.php(112): block_sharing_cart\controller-&gt;restore() #28 {main}

**Comment by coryarobbins** [comment]
Update...  This appears to be only happening for certain users.  It happens to my admin account and some teacher accounts, but I haven't figured out a pattern yet.

**Comment by plierschpl** [comment]
we have currently the same issue on our Postgres Moodle environment

`dml_read_exception: Fehler beim Lesen der Datenbank (ERROR: invalid input syntax for type bigint: "" SELECT * FROM mdl_backup_ids_temp WHERE backupid = $1 AND itemname = $2 AND itemid = $3 [array ( 0 =&gt; 'f560e6d098ea1482feb40d6c74d70949', 1 =&gt; 'course_module', 2 =&gt; '', )]) in [dirroot]/lib/dml/moodle_database.php:486 Stack trace: #0 [dirroot]/lib/dml/pgsql_native_moodle_database.php(329): moodle_database-&gt;query_end(false) #1 [dirroot]/lib/dml/pgsql_native_moodle_database.php(920): pgsql_native_moodle_database-&gt;query_end(false) #2 [dirroot]/lib/dml/moodle_database.php(1624): pgsql_native_moodle_database-&gt;get_records_sql('SELECT * FROM m...', Array, 0, 0) #3 [dirroot]/lib/dml/moodle_database.php(1596): moodle_database-&gt;get_record_sql('SELECT * FROM {...', Array, 0) #4 [dirroot]/lib/dml/moodle_database.php(1575): moodle_database-&gt;get_record_select('backup_ids_temp', 'WHERE backupid ...', Array, '*', 0) #5 [dirroot]/backup/util/dbops/restore_dbops.class.php(240): moodle_database-&gt;get_record('backup_ids_temp', Array) #6 [dirroot]/backup/util/dbops/restore_dbops.class.php(1737): restore_dbops::get_backup_ids_cached('f560e6d098ea148...', 'course_module', '') #7 [dirroot]/backup/util/plan/restore_structure_step.class.php(219): restore_dbops::get_backup_ids_record('f560e6d098ea148...', 'course_module', '') #8 [dirroot]/backup/util/plan/restore_structure_step.class.php(211): restore_structure_step-&gt;get_mapping('course_module', '') #9 [dirroot]/backup/moodle2/restore_stepslib.php(2716): restore_structure_step-&gt;get_mappingid('course_module', '') #10 [dirroot]/backup/util/plan/restore_structure_step.class.php(137): restore_badges_structure_step-&gt;process_parameter(Object(stdClass)) #11 [dirroot]/backup/util/helper/restore_structure_parser_processor.class.php(121): restore_structure_step-&gt;process(Array) #12 [dirroot]/backup/util/xml/parser/processors/grouped_parser_processor.class.php(178): restore_structure_parser_processor-&gt;dispatch_chunk(Array) #13 [dirroot]/backup/util/helper/restore_structure_parser_processor.class.php(109): grouped_parser_processor-&gt;postprocess_chunk(Array) #14 [dirroot]/backup/util/xml/parser/processors/simplified_parser_processor.class.php(148): restore_structure_parser_processor-&gt;postprocess_chunk(Array) #15 [dirroot]/backup/util/xml/parser/processors/progressive_parser_processor.class.php(92): simplified_parser_processor-&gt;process_chunk(Array) #16 [dirroot]/backup/util/xml/parser/progressive_parser.class.php(190): progressive_parser_processor-&gt;receive_chunk(Array) #17 [dirroot]/backup/util/xml/parser/progressive_parser.class.php(278): progressive_parser-&gt;publish(Array) #18 [internal function]: progressive_parser-&gt;end_tag(Resource id #576, 'parameter') #19 [dirroot]/backup/util/xml/parser/progressive_parser.class.php(179): xml_parse(Resource id #576, '&lt;?xml version="...', true) #20 [dirroot]/backup/util/xml/parser/progressive_parser.class.php(158): progressive_parser-&gt;parse('&lt;?xml version="...', true) #21 [dirroot]/backup/util/plan/restore_structure_step.class.php(110): progressive_parser-&gt;process() #22 [dirroot]/backup/util/plan/base_task.class.php(181): restore_structure_step-&gt;execute() #23 [dirroot]/backup/util/plan/base_plan.class.php(191): base_task-&gt;execute() #24 [dirroot]/backup/util/plan/restore_plan.class.php(168): base_plan-&gt;execute() #25 [dirroot]/backup/controller/restore_controller.class.php(394): restore_plan-&gt;execute() #26 [dirroot]/blocks/sharing_cart/classes/controller.php(537): restore_controller-&gt;execute_plan() #27 [dirroot]/blocks/sharing_cart/restore.php(118): block_sharing_cart\controller-&gt;restore(6581, 721, 0) #28 {main}`

**Comment by donhinkelman** [comment]
Thank you for reporting this, Coryarobins and Plierschpl. Are there other PostgreSQL users with this same problem?

**Comment by AraPraxis** [comment]
Since no updates have been emitted, we see the issue as closed.

If the problem still occurs on Moodle 4.0+ then you're welcome to create a new issue regarding the error, but we will not update the sharing cart prior to Moodle 4.0 - However we do follow the Moodle releases and are willing to fix any security risks regarding this plugin.
https://moodledev.io/general/releases

Kind regards,
Anders Rasmussen

Praxis Team
