### ISSUE TITLE
Include availability restrictions when handling whole sections through sharing cart

### ISSUE THREAD

**Issue by abias** [donhinkelman/moodle-block_sharing_cart#63]
Back then when the feature to add whole sections to and restore whole sections from sharing cart was funded by Ulm university, availability restrictions were not included due to budget constraints. Unfortunately, this gap is still there today.

Steps to reproduce:
* Login as teacher
* Go to a course A
* Fill a section with some activities
* Add some availability restriction to the section, for example a date restriction
* Copy the whole section to the sharing cart
* Go to a course B
* Restore the section into the course

Expected result:
* The section is restored and contains all activities like it was in course A
* The section has the same activity restriction set like it was in course A

Actual result:
* The section is restored and contains all activities like it was in course A
* The section does not have any activity restriction

I am mainly creating this issue to make sure that this gap does not get lost and is documented, but I would surely appreciate if someone has time to finally implement it.

**Comment by donhinkelman** [comment]
Assigned section copy programmer, Ponlawat Weerapanpisit, to this issue since he is familiar with this code.

**Comment by donhinkelman** [comment]
This feature was done, merged and closed.

**Comment by abias** [comment]
Hi @donhinkelman and @ponlawat-w ,

I have quickly tested the latest version of block_sharing_cart and would like to thank you for implementing this feature to make the section copy functionality complete finally!

Cheers,
Alex
