### ISSUE TITLE
Continue to publish releases to Moodle plugin repo

### ISSUE THREAD

**Issue by abias** [donhinkelman/moodle-block_sharing_cart#65]
Dear Don, dear Praxis team,

looking at https://moodle.org/plugins/pluginversions.php?plugin=block_sharing_cart, I see that the last public release of this plugin for Moodle 3.8 was in june this year. However, looking at https://github.com/donhinkelman/moodle-block_sharing_cart/blob/MOODLE_38_STABLE/README.md, I see that multiple releases have followed after that in Github only.

As we strive to deploy plugins from the Moodle plugin repo rather than from Github for multiple reasons, especially based on the fact that the Moodle plugin repo releases are explicitely released as stable and you never now about the production-readyness of particular Github branches, I would like to encourage you to continue to publish your releases to the Moodle plugin repo.

Thank you very much for supporting the Moodle community with this plugin.

Cheers,
Alex

**Comment by abias** [comment]
I have just spotted #64 which seems to bring a new release and was created 3 hours before I created this issue. If my assumption is right, please excuse my impatience and keep up the good work!

**Comment by donhinkelman** [comment]
Hi Alex,

Thanks for pointing out the delay in plugin repo releases. It is my job to release on moodle.org while Praxis handles the Github work. I also try to reproduce the issues reported in github. I will try to get out a Moodle.org release tonight which includes Sharing Cart 3.8, release 17.  Again sorry for the delay. And if I update version.php files or readme files incorrectly, please alert me. I am still learning. Thanks.  
Don

**Comment by abias** [comment]
Thanks Don, for tackling this issue and for releasing a new version to moodle.org/plugins!
Then this issue can be closed :)

Cheers,
Alex
