### ISSUE TITLE
Improve UX of the "Copy whole section" widget in the Sharing cart block view

### ISSUE THREAD

**Issue by abias** [donhinkelman/moodle-block_sharing_cart#67]
Hi Don, dear Praxis team,

while upgrading to Moodle 3.9 and Sharing Cart 3.8 Release 10, I saw that you have included a "Copy whole section" widget which can be directly used from within the Sharing cart block view:

![image](https://user-images.githubusercontent.com/1092118/94234150-660ae500-ff09-11ea-99a2-058ea1a96e80.png)

I see three minor problems with this widget:

1. The widget should be better separated from the sharing cart's content list. It is a separate feature.
2. The widget is not clearly explaining what it is there for. "Copy section" can be misunderstood, e.g. that the teacher could copy everything from the cart's content list to the given section.
3. On Boost child themes which have been modified in a way that the right column is smaller (our theme_boost_campus has this option), the button may have two lines which looks ugly then:
![image](https://user-images.githubusercontent.com/1092118/94234537-27c1f580-ff0a-11ea-88ae-18b40ebfced7.png)

I would propose two things:
1. Please spend some more space for this feature to better explain what it's doing and to prevent like wraps on smaller column widths. For example:
![image](https://user-images.githubusercontent.com/1092118/94235087-48d71600-ff0b-11ea-966d-3ec06dd42b6d.png)
2. Please add an admin setting to allow admins to disable this widget in case they are already happy with the "Copy to sharing cart" icon which is still placed near each section title.

Cheers,
Alex

**Comment by abias** [comment]
I would like to point out that this problem still persists in Version 3.9, release 3. But I think that it should be easy to fix.

**Comment by donhinkelman** [comment]
I agree with Alex's suggestion, and in my case, I would use an admin setting to disable the widget. For me, the "copy to sharing cart" icon next to the section title is best.
