### ISSUE TITLE
Avoid misunderstanding of the "Copy to sharing cart" icon as inactive

### ISSUE THREAD

**Issue by abias** [donhinkelman/moodle-block_sharing_cart#68]
Hi Don, dear Praxis team,

while upgrading to Moodle 3.9 and Sharing Cart 3.8 Release 10, I saw that you have pulled the "Copy to sharing cart" functionality out from the activity edit menu and have changed it to a dedicated icon:

![image](https://user-images.githubusercontent.com/1092118/94236922-49bd7700-ff0e-11ea-97d0-1d44944477b2.png)

While I appreciate this change, I am afraid that the fact that you are showing the icon with a very light tone of the brand color and are changing it to a solid color only while hovering can produce misunderstandings for users who think that the icon is disabled. And, because of the low contract, it can trigger accessibility problems as well, of course.

I would like to ask you to rethink this choice and use a more solid color when not hovered.
Ideally, use the group icons of Moodle core as example:

![image](https://user-images.githubusercontent.com/1092118/94237104-9bfe9800-ff0e-11ea-9f8e-e7eb0b71c0f6.png)

They have a solid color when not hovered, but they also have a small hovering effect.

Thanks for your consideration.

Cheers,
Alex

**Comment by Kathrin84** [comment]
He there,

Alex asked me to add my insights.

The reason for this appearance is this rule:
```
.add-to-sharing-cart {
    opacity: 1;
}
```
(https://github.com/donhinkelman/moodle-block_sharing_cart/blob/2aef67b212c48bc13caa5df6e313899f4ba1a660/styles.css#L127)

In our individual theme RAW SCSS, we changed this back to full opacity. Even with full opacity, there is still a hovering effect.

Best, Kathrin

**Comment by abias** [comment]
I would like to point out that this problem still persists in Version 3.9, release 3. But I think that it should be easy to fix.

**Comment by AraPraxis** [comment]
CSS, styling and functionality has been updated in Moodle 4.0+ releases.

We do not intent to make any updates to sharing cart prior to Moodle 4.0 - However we do follow the Moodle releases and are willing to fix any security risks regarding this plugin.
https://moodledev.io/general/releases

Kind regards,
Anders Rasmussen

Praxis Team
