### ISSUE TITLE
Improve look of "Copying this shared item" notification

### ISSUE THREAD

**Issue by abias** [donhinkelman/moodle-block_sharing_cart#69]
Hi Don, dear Praxis team,

while upgrading to Moodle 3.9 and Sharing Cart 3.8 Release 10, I had a look at the nice look & feel improvements which have been realized by you, but I also saw that the "Copying this shared item" notification is fully unstyled and thus quite ugly:

![image](https://user-images.githubusercontent.com/1092118/94237877-cd2b9800-ff0f-11ea-93c6-1528d68f7d58.png)

On https://github.com/donhinkelman/moodle-block_sharing_cart/blob/master/styles.css#L93-L99, there would be styles to style this notification with a dashed border similar to the drop zone, but maybe the .clipboard element got moved out of the .course-content element in some previous commit so that the selector does not apply anymore?

Against this background, I would like to ask you to have a look at this unstyled notification and, at least, fix the CSS selectors so that they apply again but, even better, change the notification into a nicely looking notification which matches Moodle core's look & feel.

Thanks in advance!

Cheers,
Alex

**Comment by abias** [comment]
I would like to point out that this problem still persists in Version 3.9, release 3. But I think that it should be easy to fix.

**Comment by donhinkelman** [comment]
Good suggestion and I hope Praxis will have time for these many minor fixes. Soon I will be making a 3.10 release, but this problem will still persist.

**Comment by frederikmillingpytlick** [comment]
Closing issue, this has been implemented
![billede](https://user-images.githubusercontent.com/78727001/207537223-d9358b0a-0f7f-4cfa-a9b8-470a9e33092a.png)
