### ISSUE TITLE
Moodle 3.9 version, 3.10 version, 3.11 version?

### ISSUE THREAD

**Issue by Urpokarhu1** [donhinkelman/moodle-block_sharing_cart#72]
Hello,

When is Moodle 3.9 version going to be released?

**Comment by donhinkelman** [comment]
Are you asking when will Sharing Cart version 3.9 be released?  Right now users like you are testing Sharing Cart 3.8 release 17 on their Moodle 3.9  and reporting bugs. Please try it and report any issue here on github.

**Comment by donhinkelman** [comment]
Happy New Year to all. Tomorrow, January 11, I will post the newest github version on moodle.org plugins database and label it Sharing Cart 3.9, release 1.  This will include section copy bug fixes by Ponlawat Weerapanpisit. The Sharing Cart still has minor issues in 3.9 to fix but one user has reported it works well in Moodle 3.10. If there any more fixes to add or any objection to this new release, please post here during the next 24 hours. Thanks everyone for working on the Sharing Cart this past year.

**Comment by donhinkelman** [comment]
Version 3.9, release 5 - 2021.04.26 has been released with a few minor changes. I believe we will call the next version 3.10, release 1, unless there is a report of a serious issue with 3.10. So far SC version 3.9 is working well in Moodle 3.10.

**Comment by donhinkelman** [comment]
After several pull requests by Frederik, Ponlawat, and others, I will proceed to make Sharing Cart 3.10 release 1 shortly. I have not received reports of Sharing Cart in Moodle 3.11, so I will not jump to that level until we hear of any problems or successes in the latest Moodle release.

**Comment by donhinkelman** [comment]
I have just assigned my colleagues at Praxis and other contributors to this issue, simply to act as advisors as I try to manage this github. I am still not proficient, so I really appreciate it when you just tell me what to do. It is great that you often allow me to be the one to merge pull requests, but I also do not mind if you do it directly when you are sure there is no issue in merging.
