### ISSUE TITLE
format_flexsections: sharing_cart icon doesn't appear besides activities

### ISSUE THREAD

**Issue by OdyX** [donhinkelman/moodle-block_sharing_cart#74]
On a Moodle 3.7 instance with format_flexsections, activity-level sharing cart icons don't appear at page load.

They _do_ appear, _per activity_, once said activity is moved.

**Comment by donhinkelman** [comment]
Thank you, OdyX, for reporting this issue with the flexible sections course format. I just committed a bug fix in Sharing Cart 3.11, release 3 that may solve your issue. Could you install this new version and confirm whether you have any issues?

**Comment by frederikmillingpytlick** [comment]
The reporter has not responded, closing issue.
