### ISSUE TITLE
Problem Exception : Class 'backup_execution_step' not found

### ISSUE THREAD

**Issue by plourdej228** [donhinkelman/moodle-block_sharing_cart#75]
Hi
 When I try to copy an activity it works, but when I try to paste I have the following error.

Exception : Class 'backup_execution_step' not found

Plus d'informations sur cette erreur

×Info de débogage 
Error code: generalexceptionmessage
×Trace de la pile 
line 33 of \backup\moodle2\backup_stepslib.php: Error thrown
line 26 of \report\embedquestion\backup\moodle2\backup_report_embedquestion_plugin.class.php: call to require_once()
line 283 of \backup\util\plan\restore_structure_step.class.php: call to require_once()
line 4237 of \backup\moodle2\restore_stepslib.php: call to restore_structure_step->add_plugin_structure()
line 84 of \backup\util\plan\restore_structure_step.class.php: call to restore_module_structure_step->define_structure()
line 181 of \backup\util\plan\base_task.class.php: call to restore_structure_step->execute()
line 210 of \backup\moodle2\restore_activity_task.class.php: call to base_task->execute()
line 178 of \backup\util\plan\base_plan.class.php: call to restore_activity_task->execute()
line 168 of \backup\util\plan\restore_plan.class.php: call to base_plan->execute()
line 384 of \backup\controller\restore_controller.class.php: call to restore_plan->execute()
line 505 of \blocks\sharing_cart\classes\controller.php: call to restore_controller->execute_plan()
line 116 of \blocks\sharing_cart\restore.php: call to block_sharing_cart\controller->restore()

I also put what I got in debug mode.

I test this on a fresh installation.  When I install the sharing_cart, it works fine.  After some experimentations, I found a plugins who seems to be in problem as you seen also in the previous log : report_embedquestion

This is my different versions : 
Version 3.9.2+ Build 20200918
PHP 7.4.2
Mysql 5.7.27
Sharing_cart : 3.8 release 20 : 2020101401
report_embedquestion : 1.1 for Moodle 3.6+ : 2020062800

I don't know if the probleme is in the sharing_cart or in the report_embedquestion.
Thanks for your help.

**Comment by plourdej228** [comment]
I close the case.
I've search on the report_embedquestion page and they have a temporary solution.  It's to delete the backup folder in /report/embedquestion.

Thanks!

**Comment by englishwebtls** [comment]
This works for me too, thanks for the advice.
But why?
