### ISSUE TITLE
loss of configuration when copying Topics	

### ISSUE THREAD

**Issue by doiphode** [donhinkelman/moodle-block_sharing_cart#76]
When using the sharing cart to copy entire topics, any restrictions which have been added to the topic are stripped out when it is copied into the other course area.

**Comment by abias** [comment]
I think this is a duplicate of #63

**Comment by donhinkelman** [comment]
Thank you, diophode, for reporting this issue. I will close this issue as a duplicate, and see if we can move on Issue #63.
