### ISSUE TITLE
Error when copying HP5 activities on Moodle 3.9

### ISSUE THREAD

**Issue by jonlucholmes** [donhinkelman/moodle-block_sharing_cart#78]
Moodle version: 3.9.2+ (Build: 20201030)
Plugin version: 3.9, release 17 (Build: 2020090100)
H5P Plugin version: 2020080400

Copying a section with H5P activities throws a sharing cart error message on Moodle 3.9. This is using the H5P implementation that's a Moodle plugin, not the H5P implement that was added to core Moodle with 3.8/3.9

![image](https://user-images.githubusercontent.com/9091061/99279765-82037680-2828-11eb-94ae-b41a8f5b83cd.png)

**Comment by donhinkelman** [comment]
I wonder if this is still happening with Sharing Cart 3.9 release 3? Thank you for waiting for my late reply.

**Comment by dasistwas** [comment]
Still the same @donhinkelman 
`

[Mon May 10 23:03:19.045261 2021] [proxy_fcgi:error] [pid 771828:tid 140220909463296] (70007)The timeout specified has expired: [client 144.65.16.160:0] AH01075: Error dispatching request to : (polling), referer: https://www.eduvidual.at/course/view.php?id=XXXXX&notifyeditingon=1`

**Comment by donhinkelman** [comment]
Thank you for checking @dasistwas. H5P activities from different versions and types (Moodle plugin vs. core) are also causing problems in standard backup/restore in some Moodle cases. I don't know how to solve this but your bug report is in my radar. By the way, a few more issues have been resolved in Sharing Cart Version 3.9, release 5 - 2021.04.26.

**Comment by dannywelz** [comment]
Hey i just discovered the reason. H5P is saving his libraries within the moodle backup functions. This is a known issue within the h5p community. This fact is the reason for slow backups of h5p activitys within a moodle instance in generell.
To fix this problem you can simply add $CFG->mod_hvp_backup_libraries = '0'; to the moodle config. This disables saving those libraries

**Comment by dannywelz** [comment]
Hey i just discovered the reason. H5P is saving his libraries within the moodle backup functions. This is a known issue within the h5p community. This fact is the reason for slow backups of h5p activitys within a moodle instance in generell.
To fix this problem you can simply add $CFG->mod_hvp_backup_libraries = '0'; to the moodle config. This disables saving those libraries

**Comment by AraPraxis** [comment]
Since no updates have been emitted, we see the issue as closed.

If the problem still occurs on Moodle 4.0+ then you're welcome to create a new issue regarding the error, but we will not update the sharing cart prior to Moodle 4.0 - However we do follow the Moodle releases and are willing to fix any security risks regarding this plugin.
https://moodledev.io/general/releases

Kind regards,
Anders Rasmussen

Praxis Team
