### ISSUE TITLE
Course module backup menu item isn't added properly

### ISSUE THREAD

**Issue by johnnypraxis** [donhinkelman/moodle-block_sharing_cart#8]
Sometimes the value of the "data-action" attribute isn't changed to "backup" when the first menu element is cloned and called "Copy to Sharing Cart".

This means the backup action doesn't work as expected. Both the dublicate and the backup action is called when the new cloned menu item (Copy to Sharing Cart) is clicked and that results in a "nopermission" popup. See screenshot:
![image](https://user-images.githubusercontent.com/11717570/53555109-93cb5480-3b41-11e9-8801-bc217b2b4fd6.png)

Unfortunately I can't say exactly how to reproduce this bug but this pull request fixes the bug:
https://github.com/donhinkelman/moodle-block_sharing_cart/pull/7

**Comment by donhinkelman** [comment]
This issue has been merged into the master, and now closed. Thank you, JohnnyPraxis!
