### ISSUE TITLE
Javascript Caching causes buttons to freeze in 3.10

### ISSUE THREAD

**Issue by nelliemuller** [donhinkelman/moodle-block_sharing_cart#81]
It’s back. I deleted all my outdated and latest  plugins. It was fine with Safari until I upgraded my Apple OS but the problem existed with Chrime and every other browser. I tried it in Boost in case it was a theme thing but the buttons froze when I enable JavaScript. I’m wondering if it could be Google Meet fir Moodle which is what i need the JavaScript for.

**Comment by donhinkelman** [comment]
Hi Nellie, thanks for testing the Sharing Cart in Moodle 3.10. I am still using 3.9, so you may be the first one to report a 3.10 bug. Holidays are starting now, but I hope Praxis can get to this first thing in the new year.

**Comment by nelliemuller** [comment]
Hi Don,

The sharing cart works perfectly on version 3.10. Thank you for doing a
great job on the plugin. My teachers and I love it.

I have issues with cache javascript. I can't enable it for Google Meet for
Moodle plugin because when I do the menus freeze.

Warm wishes,
Dr. Nellie Deutsch <http://goo.gl/7BgeKM>
Become a Patron! <https://www.patreon.com/bePatron?u=608783>
Education Technology & Leadership
Learner Autonomy Supportive Teacher

Free Online Professional Development
<http://moodle4teachers.org/course/index.php/>

How to log in using Facebook, Google, or Microsoft

https://youtu.be/jag7H5os3Gk


TESOL EVO Coordinator
<http://evosessions.pbworks.com/w/page/10708567/FrontPage>
Youtube Channel
<https://www.youtube.com/channel/UCsLt8oYvDYGpSHcGhRBBkyw?sub_confirmation=1>
Author on Amazon  <https://www.amazon.com/-/e/B005UHLKQQ>

[image: Linkedin] <http://ca.linkedin.com/in/nelliemuller>[image: Facebook]
<http://www.facebook.com/drnelliedeutsch>[image: Twitter]
<http://twitter.com/nelliemuller>

**Comment by frederikmillingpytlick** [comment]
Hi @nelliemuller, are you still having this issue, if so could you please elaborate on the details of your issue?

**Comment by nelliemuller** [comment]
Hi Don,

Everything got sorted out with the upgrade to Moodle 4.

Thank you.

Warm wishes,
Dr. Nellie Deutsch <http://goo.gl/7BgeKM>
[image: YouTube Icon Small Circle] <https://youtube.com/c/nelliedeutsch>[image:
Facebook Icon Small Circle] <https://facebook.com/drnelliedeutsch>[image:
Twitter Icon Small Circle] <https://twitter.com/nelliemuller>[image:
LinkedIn Icon Small Circle] <https://www.linkedin.com/in/nelliemuller>[image:
Link (Generic) Icon Small Circle] <https://integrating-technology.org/>
Education Technology & Leadership
Learner Autonomy Supportive Teacher
Online Professional Development <https://integrating-technology.org/>
Teachers Teaching Teachers <https://onlinecourses4free.com/>
Give and Take Online Courses <https://integratingtechnology.org/>


TESOL EVO Past / Current Lead Coordinator
<http://evosessions.pbworks.com/w/page/10708567/FrontPage>
TESOl CALL-IS Co Chair Elect <https://www.call-is.org/WP/leadership-20-21/>
Youtube Channel
<https://www.youtube.com/channel/UCsLt8oYvDYGpSHcGhRBBkyw?sub_confirmation=1>
Author on Amazon  <https://www.amazon.com/-/e/B005UHLKQQ>

Let's Meet https://calendly.com/nellie-muller-deutsch

**Comment by donhinkelman** [comment]
Thanks, Nellie, for reporting back, and thanks Frederik for viligently pursuing remaining bugs in the Sharing Cart. Closing this issue now. We all say thanks to Praxis for supporting this little plugin.  :-). Happy New Year to you all!
