### ISSUE TITLE
Doesn't work HTTP Error 500

### ISSUE THREAD

**Issue by behoof** [donhinkelman/moodle-block_sharing_cart#82]
L.s.

Using it on Moodle 3.8.2.
Copying it into the cart works
But  pasting it into the target course the target course gives an HTTP Error 500

Bert

**Comment by donhinkelman** [comment]
Hi Bert, please tell me if the latest version of Sharing Cart, 3.11 release 1 gives you the same error. If it does, then likely it is a theme or course format issue. Which theme and which course format are you using?

**Comment by frederikmillingpytlick** [comment]
No response from the reporter, closing issue
