### ISSUE TITLE
Unable to copy sections containing no activites/resources

### ISSUE THREAD

**Issue by ghost** [donhinkelman/moodle-block_sharing_cart#83]
We have just upgraded from `2018012400` to `2020090100` on Moodle 3.9.3. Our users have raised an issue that they are no longer able to copy sections that contain no activities/resources, just a summary. This is used quite often for posting information directly within sections, that don't need an activity.

This functionality appears to have been intentionally removed at some point, via a check of `$section->sequence` https://github.com/donhinkelman/moodle-block_sharing_cart/blob/master/block_sharing_cart.php#L132.

Was this an intended change? If so, what is the rationale behind it? The Moodle import feature allows copying of emptying sections, however our users are used to using the sharing cart for this.

**Comment by donhinkelman** [comment]
I agree it is useful to copy sections with no activities, only summaries or text or image labels. I will discuss this with the programmer helping with section copy.

**Comment by donhinkelman** [comment]
**Comments by Mo:**
Issue #83 about copying an empty section to cart, I believe that the current structure of the Sharing Cart does not support the existence of empty folder in a cart, therefore copying an empty section is not currently possible.
**Reply by Don**
According to the issue posting, copying an “empty” section used to be possible, but that was removed at some point.  Actually, I don’t know when that was, or if it was.

I do know that many teachers spend a lot of time making information or description at the top of the section. This contains:
-  title in the title box
-  section information under the title, which includes images, instructions, important information
-  but there are no activities in the section

So is there a way to have the Sharing Cart copy a folder that is empty of activities, but only has a title and top information?

**Comment by Mo:**
To give you some picture explaining the reason, Sharing Cart stores data in a cart like this:
For example,
- Item A, path in cart = /
- Item B, path in cart = /folderX
- Item C, path in cart = /folderX
- Item D, path in cart = /folderX/folderY
- Item E, path in cart = /folderZ
In other words, the current Sharing Cart does not store "folder" in the database, instead, it stores "items" (or activities) in the database, and each item has data value of "path in cart" indicating which "virtual folder" it is stored in (I said virtual because the folder does not really exist).
When the Sharing Cart renders the block in a course, it renders from these folder path values, and generates the folder icons in the tree. From the example above, there will be item A in the root folder, item B and C in folderX, item D in folder Y which is in folder X, and item E in folder Z.
For this reason, if we move the item E to /folderX for example, there will be no more items in the cart with /folderZ  path, and therefore the folderZ will be virtually deleted.
For the same reason, copying an empty section does not add any new item to the cart, so the folder is not created in the cart.
However, if you want, I can make an update which will change the database structure of the block to support having empty folders, and this folder stores only section data (e.g. description) without activities inside.
**Reply by Don:**
Yes, an update to do this would be great. Can the section data be included in the folder?

**Comment by ponlawat-w** [comment]
Hi,
I have created a pull request #100 to fix this issue. This fix is trying to solve the issue without chaging database structure.
It creates an empty item when an empty section is copied. This item will be invisible when rendering the cart, so the empty folders can be seen and restored to a course.

**Comment by donhinkelman** [comment]
This issue has been fixed and should have been closed earlier. Thanks to Ponlawat Weerapanpisit for work on this.
