### ISSUE TITLE
Class 'backup_execution_step' not found

### ISSUE THREAD

**Issue by englishwebtls** [donhinkelman/moodle-block_sharing_cart#87]
Sharing cart no longer working

Updated to latest sharing cart version $plugin->version = 2021011101;
$plugin->requires = 2018120300; // Moodle 3.6
$plugin->component = 'block_sharing_cart';
$plugin->release = '3.9, release 1';
$plugin->maturity = MATURITY_STABLE;

on Moodle 3.9 (Fordson Theme)
Cleared cache
Checked that file exists in /backup/util/plan/backup_execution_step.class.php
Still getting error: moodle sharing cart Class 'backup_execution_step' not found

Any suggestions?

Thanks

**Comment by frederikmillingpytlick** [comment]
Hi @englishwebtls are you still having this issue?
