### ISSUE TITLE
Sharing Cart - Error can not create file "849797/user/..."

### ISSUE THREAD

**Issue by ejohnlove** [donhinkelman/moodle-block_sharing_cart#9]
I'm not able to copy a whole Section of a course (aka, a Topic) to the Sharing Cart. It gives me an error message that says:
Sharing Cart - Error can not create file "849797/user/..."

(This error message comes very quickly after trying to "Add to Cart" on the Section, and ends with the filename of a .mbz backup file)
![section_2_sharing_cart_error_id-5151_feb282019](https://user-images.githubusercontent.com/7672892/53914073-a9dd8700-4011-11e9-8b5d-9cd63a9465c5.jpg)

This is consistently the case for a Teacher role. Our Admin users get an addt'l prompt asking them to include or exclude users before doing the copy. If we exclude users, the copy to cart always works.

Our work-around for Teachers is to not try to copy an entire section to the cart, but just copy items one-by-one from inside the section.

I'm also looking in "/admin/settings.php?section=blocksettingsharing_cart" to see if I should just give the user in question the Manager role, and if this would be an acceptable solution for her. 

Moodle version: 3.4.6+ (2017111306.06)
Sharing Cart version: 3.6, release 1, 2019012000

Appreciate your help very much!

John.

**Comment by donhinkelman** [comment]
Hi John, did elevating the role to Manager help?  Any more insights into the problem?

**Comment by TubsDK** [comment]
Hi John 

Since your ticket has been sitting idle for some while and since 3.4 is well out of support it will close the issue for now. But feel free to re-report the isse.
