### ISSUE TITLE
Mouse over button

### ISSUE THREAD

**Issue by dinism** [donhinkelman/moodle-block_sharing_cart#91]
Moodle 3.10.2
Plugin version 3.9, release 3

When passing mouse over the button i got this:
![imagem](https://user-images.githubusercontent.com/14828021/111034772-15cc0480-840f-11eb-96ca-257c087649a5.png)
Is this OK?

**Comment by marxjohnson** [comment]
I have attempted to reproduce this on Moodle 4.0, Sharing cart 4.0, release 2 and the title showed correctly as "Copy selected section". I believe this issue can be closed.
