### ISSUE TITLE
Label

### ISSUE THREAD

**Issue by dinism** [donhinkelman/moodle-block_sharing_cart#93]
Thanks for the PLUGIN.
When you want do bulk delete and one resourse is a LABEL
![imagem](https://user-images.githubusercontent.com/14828021/111036214-0dc39300-8416-11eb-84fe-40afe57258a3.png)

![imagem](https://user-images.githubusercontent.com/14828021/111036246-32b80600-8416-11eb-9bb7-aec3b58adf4c.png)

**Comment by marxjohnson** [comment]
I have reproduced this issue on Sharing Cart Version 4.0, release 2. I will attempt to provide a fix.
