### ISSUE TITLE
error when copying an activity between two lessons

### ISSUE THREAD

**Issue by SavinienTech** [donhinkelman/moodle-block_sharing_cart#94]
Hello, 

I allow myself to explain to you the problem that appears on our moodle site.

  When an instructor copies an activity between two courses through the sharing carts that also copies all the badges from the first court to the second court I specify that the copied activity has no connection with the allocation of badges.
  So we observed that a badge was copied 480,859 times (photo attached)
  The duplicated badges appear: in status Not available for users and in criteria Completed :! Please note: this activity is not available (photo attached).

one of but instructor to post on the moodle france forum which directs us to the developers of the plugin. [Link](https://moodle.org/mod/forum/discuss.php?d=419063)

Moodle version: 3.8.6+ build 20201211
Now we are in Sharing Cart 3.9, release 3, and the error will appears with the others versions of plugin.

waiting for your return 
cordially savi

![Screenshot_2021-03-02 Gérer les badges](https://user-images.githubusercontent.com/36775367/111768671-85773f00-88a8-11eb-891c-815da3873918.png)
![7855484997161727674](https://user-images.githubusercontent.com/36775367/111768775-a50e6780-88a8-11eb-8284-14ed19a07ad1.jpg)

**Comment by donhinkelman** [comment]
Hello Savi and apologies for not replying earlier. Thank you for the screenshots. This is the first issue I have seen with badges. May I confirm that this issue only happens in badges?  I have assigned this to Johnny Drud of Praxis.

**Comment by mcardle** [comment]
This is a known issue with badges and has nothing to do with the sharing cart. Have a look here: https://tracker.moodle.org/browse/MDL-43697

This was fixed in Moodle 3.9 - hope this helps.

**Comment by donhinkelman** [comment]
Thanks Ulrik, for checking this out and confirming the problem was not with the Sharing Cart.
