### ISSUE TITLE
Error with some items: Exception - Call to a member function copy_content_to() on bool

### ISSUE THREAD

**Issue by dewray** [donhinkelman/moodle-block_sharing_cart#96]
I am getting the following error when I try to paste from Sharing Cart with _some_, but not all, assignments: "Exception - Call to a member function copy_content_to() on bool"

Ubuntu 20.04
Moodle 3.10.3+ (Build: 20210330)
mariadb 10.5.9
php 7.4.3
all expected extensions.

**Comment by donhinkelman** [comment]
Thanks dewray, for reporting this issue #96 . I have assigned Johnny Drud in the Praxis team to work on this.

**Comment by frederikmillingpytlick** [comment]
Hi @dewray do you still experience this issue?

**Comment by dewray** [comment]
I do not experience it any longer, I'm afraid. I'm now using
Moodle 4.1+ (build 22011209)
Ubuntu 22.04
mariadb 10.6.11
php 7.4.33
I have not done extensive testing, however.

**Comment by frederikmillingpytlick** [comment]
As no other users seem to be experiencing this issue either, I'm closing it until further notice.
